### ISSUE TITLE
PlexRequests.UI has stopped working

### ISSUE THREAD

**Issue by heartisall** [tidusjar/PlexRequests.Net#119]
About once per day I am getting this error. I was also getting it with 1.4.1 but I thought it was due to a bad upgrade on my part. With 1.5.2 I set it back up from scratch. This is on a Server 2012R2 box with nothing else running currently. I am getting this error when it happens:

`Version: 1.5.2
Request Plex is running on the following: http://+:3579/
Press any key to exit

Unhandled Exception: System.ApplicationException: Error retrieving response. Che
ck inner details for more info. ---> System.Net.WebException: The request was ab
orted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.GetResponse()
   at RestSharp.Http.GetRawResponse(HttpWebRequest request)
   at RestSharp.Http.GetResponse(HttpWebRequest request)
   --- End of inner exception stack trace ---
   at PlexRequests.Api.ApiRequest.ExecuteXml[T](IRestRequest request, Uri baseUr
i) in C:\projects\requestplex\PlexRequests.Api\ApiRequest.cs:line 80
   at PlexRequests.Api.PlexApi.SearchContent(String authToken, String searchTerm
, Uri plexFullHost) in C:\projects\requestplex\PlexRequests.Api\PlexApi.cs:line
113
   at PlexRequests.Services.PlexAvailabilityChecker.CheckAndUpdateAll(Int64 chec
k) in C:\projects\requestplex\PlexRequests.Services\PlexAvailabilityChecker.cs:l
ine 71
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   at System.Reactive.Linq.ObservableImpl.Timer.TimerImpl.Tick(Int64 count)
   at System.Reactive.Concurrency.DefaultScheduler.<>c__DisplayClass9`1.<Schedul
ePeriodic>b__7()
   at System.Reactive.Concurrency.AsyncLock.Wait(Action action)
   at System.Reactive.Concurrency.DefaultScheduler.<>c__DisplayClass9`1.<Schedul
ePeriodic>b__6()
   at System.Reactive.Concurrency.DefaultConcurrencyAbstractionLayer.PeriodicTim
er.Tick(Object state)
   at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback()
`

**Comment by tidusjar** [comment]
It could possibly be because the request is falling back to SSL3, I've changed it so we not specify a security protocol type of TLS so this should fix it.

How urgent is this?

**Comment by heartisall** [comment]
Thanks @tidusjar . It's not super urgent when I see the domain not resolving I just login to the server and restart the .exe . I can wait for the next release, just wanted to bring it to your attention. Thanks for the help

**Comment by tidusjar** [comment]
Well thank you for letting me know! :)
