### ISSUE TITLE
PlexRequest crashing

### ISSUE THREAD

**Issue by csy7550** [tidusjar/PlexRequests.Net#171]
#### Plex Requests.Net Version:

1.6.1

#### Operating System:

Windows 8.1

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Application: PlexRequests.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Net.Sockets.SocketException
   at System.Net.Sockets.Socket.DoConnect(System.Net.EndPoint, System.Net.SocketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean, System.Net.Sockets.Socket, System.Net.Sockets.Socket, System.Net.Sockets.Socket ByRef, System.Net.IPAddress ByRef, ConnectSocketState, System.IAsyncResult, System.Exception ByRef)

Exception Info: System.Net.WebException
   at System.Net.HttpWebRequest.GetResponse()
   at RestSharp.Http.GetRawResponse(System.Net.HttpWebRequest)
   at RestSharp.Http.GetResponse(System.Net.HttpWebRequest)

Exception Info: System.ApplicationException
   at PlexRequests.Api.ApiRequest.Execute[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](RestSharp.IRestRequest, System.Uri)
   at PlexRequests.Api.CouchPotatoApi.GetMovies(System.Uri, System.String, System.String[])
   at PlexRequests.Services.CouchPotatoCacher.Queued(Int64)
   at System.Reactive.AnonymousSafeObserver`1[[System.Int64, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].OnNext(Int64)
   at System.Reactive.Linq.ObservableImpl.Timer+TimerImpl.Tick(Int64)
   at System.Reactive.Concurrency.DefaultScheduler+<>c__DisplayClass9`1[[System.Int64, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<SchedulePeriodic>b__7()
   at System.Reactive.Concurrency.AsyncLock.Wait(System.Action)
   at System.Reactive.Concurrency.DefaultScheduler+<>c__DisplayClass9`1[[System.Int64, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<SchedulePeriodic>b__6()
   at System.Reactive.Concurrency.DefaultConcurrencyAbstractionLayer+PeriodicTimer.Tick(System.Object)
   at System.Threading.TimerQueueTimer.CallCallbackInContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireQueuedTimerCompletion(System.Object)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

```

#### Reproduction Steps:

Leave PlexRequest running for some time. This has happend 2 times now, same error. Should note that this is from the windows event log as plexrequest log doesn't say anything about this.

**Comment by tidusjar** [comment]
Thanks, @Drewster727 are you able to comment on this? You are more familiar with the CP Cacher

**Comment by Drewster727** [comment]
This could be something similar to what I'm running into under linux/mono. I'll have to confirm. Interesting that the logs didn't show this and you had to grab it from the event viewer.

**Comment by heartisall** [comment]
@csy7550 @tidusjar I think this is likely the same issue I was having on Server 2012. On the Newest release I changed the .exe to run in compatibility mode (Windows 7) and I have not had a crash since vs. before at least 1 or 2 per day.

**Comment by csy7550** [comment]
@heartisall I'll try that :)

**Comment by csy7550** [comment]
@heartisall Does not make a difference, crashed during the night

**Comment by tidusjar** [comment]
Same error logs @csy7550 ?

**Comment by csy7550** [comment]
Actually no, but kind of (!) SickRage this time.

Application: PlexRequests.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Net.Sockets.SocketException
   at System.Net.Sockets.Socket.DoConnect(System.Net.EndPoint, System.Net.SocketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean, System.Net.Sockets.Socket, System.Net.Sockets.Socket, System.Net.Sockets.Socket ByRef, System.Net.IPAddress ByRef, ConnectSocketState, System.IAsyncResult, System.Exception ByRef)

Exception Info: System.Net.WebException
   at System.Net.HttpWebRequest.GetResponse()
   at RestSharp.Http.GetRawResponse(System.Net.HttpWebRequest)
   at RestSharp.Http.GetResponse(System.Net.HttpWebRequest)

Exception Info: System.ApplicationException
   at PlexRequests.Api.ApiRequest.Execute[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](RestSharp.IRestRequest, System.Uri)
   at PlexRequests.Api.SickrageApi+<>c__DisplayClass9_0.<GetShows>b__0()
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at PlexRequests.Api.SickrageApi+<GetShows>d__9.MoveNext()

Exception Info: System.AggregateException
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean)
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetResultCore(Boolean)
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].get_Result()
   at PlexRequests.Services.SickRageCacher.Queued(Int64)
   at System.Reactive.AnonymousSafeObserver`1[[System.Int64, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].OnNext(Int64)
   at System.Reactive.Linq.ObservableImpl.Timer+TimerImpl.Tick(Int64)
   at System.Reactive.Concurrency.DefaultScheduler+<>c__DisplayClass9`1[[System.Int64, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<SchedulePeriodic>b__7()
   at System.Reactive.Concurrency.AsyncLock.Wait(System.Action)
   at System.Reactive.Concurrency.DefaultScheduler+<>c__DisplayClass9`1[[System.Int64, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<SchedulePeriodic>b__6()
   at System.Reactive.Concurrency.DefaultConcurrencyAbstractionLayer+PeriodicTimer.Tick(System.Object)
   at System.Threading.TimerQueueTimer.CallCallbackInContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback()

**Comment by tidusjar** [comment]
We throw an `ApplicationException` (could be a better exception type) when the response from the API call contains errors. It looks like in the cachers we need to catch that exception type and handle it better to stop PR from crashing.

**Comment by tidusjar** [comment]
Anyone want to try out a new build to see if it resolves the issue?

**Comment by csy7550** [comment]
@tidusjar I would love to try :)

**Comment by tidusjar** [comment]
@csy7550 https://ci.appveyor.com/project/tidusjar/requestplex/build/1.6.287/artifacts

Let me know how you get on!

**Comment by csy7550** [comment]
Up and running, will report back!

**Comment by csy7550** [comment]
@tidusjar Been running since yesterday now without any crashes, looks promising!

I might have found a HUGE memory leak though, have to confirm first, then report new issue.

**Comment by csy7550** [comment]
@tidusjar I think it's safe to say the problem is gone. Should have crashed multiple times by now. Great!
