### ISSUE TITLE
CouchPotato API Communication Issue

### ISSUE THREAD

**Issue by ptcfast2** [tidusjar/PlexRequests.Net#180]
**Plex Requests.Net Version:** 1.6.1
**CouchPotato Version:** c4fad95c (2/24/2016) cloned from git
**Operating System:** Windows Server 2012 R2 Standard
**Mono Version:** N/A
**Applicable Logs:**

> C:\projects\requestplex\PlexRequests.Api\ApiRequest.cs:line 69
   at PlexRequests.Api.CouchPotatoApi.GetProfiles(Uri url, String apiKey) in C:\projects\requestplex\PlexRequests.Api\CouchPotatoApi.cs:line 108
   at PlexRequests.Core.Setup.CacheCouchPotatoQualityProfiles(MemoryCacheProvider cacheProvider) in C:\projects\requestplex\PlexRequests.Core\Setup.cs:line 156
2016/04/24 13:00:13.531 PlexRequests.UI.Modules.ApplicationTesterModule Warn: Exception thrown when attempting to get CP's status:  
2016/04/24 13:00:13.625 PlexRequests.UI.Modules.ApplicationTesterModule Warn: System.ApplicationException: Error retrieving response. Check inner details for more info. ---> System.Xml.XmlException: 'doctype' is an unexpected token. The expected token is 'DOCTYPE'. Line 2, position 3.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(String expectedToken1, String expectedToken2)
   at System.Xml.XmlTextReaderImpl.ParseDoctypeDecl()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
   at RestSharp.Deserializers.XmlDeserializer.Deserialize[T](IRestResponse response)
   at RestSharp.RestClient.Deserialize[T](IRestRequest request, IRestResponse raw)
   --- End of inner exception stack trace ---
   at PlexRequests.Api.ApiRequest.Execute[T](IRestRequest request, Uri baseUri) in 

![image](https://cloud.githubusercontent.com/assets/16966701/14770184/2702cc48-0a20-11e6-9502-0c89d5fe0ed0.png)

**Reproduction Steps:** Utilize a CouchPotato server running on CentOS 7. Populate the necessary fields in the CouchPotato section of the Admin UI. Test connection. Encounter error.

**Comment by ptcfast2** [comment]
So uhhhh...by mashing the test connectivity button over and over and adding a forward slash at the end of the key and then removing it something started working. I don't know what, I don't know how but eventually it connected.

Let me know if you want me to nab anything from the requests PlextRequests would ask for from CouchPotato.

**Comment by tidusjar** [comment]
This issue usually happens when we hit couchpotato but can't authenticate correctly either due to bad credentials or not hitting the correct endpoint. Thanks for reporting it.
