### ISSUE TITLE
500 Error when first launch

### ISSUE THREAD

**Issue by harroguk** [tidusjar/PlexRequests.Net#19]
Downloaded the latest release.
OS Server 2008 R2
.NET 4.6

Launch PlexRequest.exe

Server running on port 3579

Browse to localhost:3579

Nancy.RequestExecutionException: Oh noes! ---> Nancy.ViewEngines.ViewNotFoundException: Unable to locate view 'Index'
Currently available view engine extensions: sshtml,html,htm
Locations inspected: views/userlogin/UserLogin/Index-en,views/userlogin/UserLogin/Index,userlogin/UserLogin/Index-en,userlogin/UserLogin/Index,views/userlogin/Index-en,views/userlogin/Index,userlogin/Index-en,userlogin/Index,views/UserLogin/Index-en,views/UserLogin/Index,UserLogin/Index-en,UserLogin/Index,views/Index-en,views/Index,Index-en,Index
Root path: C:\Users\Administrator\Desktop\Release\
If you were expecting raw data back, make sure you set the 'Accept'-header of the request to correct format, for example 'application/json'
   at Nancy.ViewEngines.DefaultViewFactory.GetRenderedView(String viewName, Object model, ViewLocationContext viewLocationContext)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at CallSite.Target(Closure , CallSite , DefaultViewFactory , Object , Object , ViewLocationContext )
   at Nancy.ViewEngines.DefaultViewFactory.RenderView(String viewName, Object model, ViewLocationContext viewLocationContext)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at CallSite.Target(Closure , CallSite , IViewFactory , String , Object , ViewLocationContext )
   at Nancy.Responses.Negotiation.ViewProcessor.Process(MediaRange requestedMediaRange, Object model, NancyContext context)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at CallSite.Target(Closure , CallSite , IResponseProcessor , String , Object , NancyContext )
   at Nancy.Responses.Negotiation.DefaultResponseNegotiator.NegotiateResponse(IEnumerable`1 compatibleHeaders, NegotiationContext negotiationContext, NancyContext context)
   at Nancy.Responses.Negotiation.DefaultResponseNegotiator.CreateResponse(IList`1 compatibleHeaders, NegotiationContext negotiationContext, NancyContext context)
   at Nancy.Responses.Negotiation.DefaultResponseNegotiator.NegotiateResponse(Object routeResult, NancyContext context)
   at Nancy.Routing.DefaultRouteInvoker.<>c__DisplayClassa.b__6(Task`1 completedTask)
   --- End of inner exception stack trace ---
   at Nancy.NancyEngine.InvokeOnErrorHook(NancyContext context, ErrorPipeline pipeline, Exception ex)

**Comment by tidusjar** [comment]
When you downloaded the .Zip did you right click and unblock it?

Windows blocks zip files from unknown sources.

**Comment by harroguk** [comment]
Yup, unblocked

**Comment by harroguk** [comment]
Found a log file...

2016/03/17 07:35:07.924 PlexRequests.UI.Program Trace: Getting product version
2016/03/17 07:35:07.931 PlexRequests.UI.Program Info: Version: 1.2.1
2016/03/17 07:35:07.967 PlexRequests.Store.DbConfiguration Trace: Checking DB
2016/03/17 07:35:07.967 PlexRequests.Store.DbConfiguration Trace: DB doesn't exist, creating a new one
2016/03/17 07:35:08.438 PlexRequests.UI.Program Trace: Getting startup URI
2016/03/17 07:35:08.549 PlexRequests.UI.Program Trace: Port: 0
2016/03/17 07:37:09.390 PlexRequests.Services.PlexAvailabilityChecker Warn: A setting is null, Ensure Plex is configured correctly, and we have a Plex Auth token.
2016/03/17 07:39:09.390 PlexRequests.Services.PlexAvailabilityChecker Warn: A setting is null, Ensure Plex is configured correctly, and we have a Plex Auth token.
2016/03/17 07:41:09.400 PlexRequests.Services.PlexAvailabilityChecker Warn: A setting is null, Ensure Plex is configured correctly, and we have a Plex Auth token.

**Comment by tidusjar** [comment]
I'm just about the leave for work. I'll check this as soon as I get in. Can you just double check that the Nancy.ViewEngine.dll is not blocked by right clicking and selecting properties?

**Comment by harroguk** [comment]
Its okay, sorted it.

Problem was that I was unblocking the EXE, not the ZIP (before extraction). 

Running the below powershell on the directory fixed the issue.

gci c:\installedprograms\plexrequests | Unblock-File
