### ISSUE TITLE
wont start fresh install

### ISSUE THREAD

**Issue by m1e1w1** [tidusjar/PlexRequests.Net#20]
500 internal server error on first run:

Nancy.RequestExecutionException: Oh noes! ---> Nancy.ViewEngines.ViewNotFoundException: Unable to locate view 'Index'
Currently available view engine extensions: sshtml,html,htm
Locations inspected: views/userlogin/UserLogin/Index-en-US,views/userlogin/UserLogin/Index,userlogin/UserLogin/Index-en-US,userlogin/UserLogin/Index,views/userlogin/Index-en-US,views/userlogin/Index,userlogin/Index-en-US,userlogin/Index,views/UserLogin/Index-en-US,views/UserLogin/Index,UserLogin/Index-en-US,UserLogin/Index,views/Index-en-US,views/Index,Index-en-US,Index
Root path: C:\plexrequestsnet\
If you were expecting raw data back, make sure you set the 'Accept'-header of the request to correct format, for example 'application/json'
   at Nancy.ViewEngines.DefaultViewFactory.GetRenderedView(String viewName, Object model, ViewLocationContext viewLocationContext)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at Nancy.ViewEngines.DefaultViewFactory.RenderView(String viewName, Object model, ViewLocationContext viewLocationContext)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at Nancy.Responses.Negotiation.ViewProcessor.Process(MediaRange requestedMediaRange, Object model, NancyContext context)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at Nancy.Responses.Negotiation.DefaultResponseNegotiator.NegotiateResponse(IEnumerable`1 compatibleHeaders, NegotiationContext negotiationContext, NancyContext context)
   at Nancy.Responses.Negotiation.DefaultResponseNegotiator.CreateResponse(IList`1 compatibleHeaders, NegotiationContext negotiationContext, NancyContext context)
   at Nancy.Responses.Negotiation.DefaultResponseNegotiator.NegotiateResponse(Object routeResult, NancyContext context)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at Nancy.Routing.DefaultRouteInvoker.<>c__DisplayClassa.b__6(Task`1 completedTask)
   --- End of inner exception stack trace ---
   at Nancy.NancyEngine.InvokeOnErrorHook(NancyContext context, ErrorPipeline pipeline, Exception ex)

thoughts?

**Comment by tidusjar** [comment]
Yes, this is happening because you need to unblock the `.zip` before extraction.

Please right click the `.zip` and press properties, then unblock. If you then extract it, the application will function correctly.

**Comment by tidusjar** [comment]
Has this been resolved @m1e1w1  ?

**Comment by m1e1w1** [comment]
yes, resolved after unblocked.
