### ISSUE TITLE
Program Keeps Crashing

### ISSUE THREAD

**Issue by williamray507** [tidusjar/PlexRequests.Net#202]
#### Operating System: Windows Server 2012R2

My system is as follows:
OS: Windows Server 2012 R2 Standard
Processor: AMD Fx-6300 Six-Core Processor 3.50 GHz
RAM: 32GB
PlexRequests is running out of the following directory: C:\PlexRequests\Release
It will run for a few hours at most before crashing.

#### Applicable Logs (from `/logs/` directory or the Admin page):
2016/05/02 17:21:18.838 PlexRequests.UI.Program Trace: Getting product version
2016/05/02 17:21:18.853 PlexRequests.UI.Program Info: Version: 1.6.1
2016/05/02 17:21:18.853 PlexRequests.Store.DbConfiguration Trace: Checking DB
2016/05/02 17:21:19.338 PlexRequests.Core.Setup Info: Executing GetSettings call to CouchPotato for quality profiles
2016/05/02 17:21:19.338 PlexRequests.Core.Setup Info: Executing GetSettings call to Sonarr for quality profiles
2016/05/02 17:21:19.556 PlexRequests.Core.Setup Info: Begin executing GetProfiles call to CouchPotato for quality profiles 
2016/05/02 17:21:19.588 PlexRequests.Core.Setup Info: Begin executing GetProfiles call to Sonarr for quality profiles 
2016/05/02 17:21:19.634 PlexRequests.Core.Setup Info: Finished executing GetProfiles call to Sonarr for quality profiles 
2016/05/02 17:21:20.650 PlexRequests.Core.Setup Info: Finished executing GetProfiles call to CouchPotato for quality profiles 
2016/05/02 17:21:22.900 PlexRequests.Services.PlexAvailabilityChecker Info: There are no requests to check. 
2016/05/02 17:31:22.767 PlexRequests.Services.PlexAvailabilityChecker Info: There are no requests to check. 
2016/05/02 17:41:22.865 PlexRequests.Services.PlexAvailabilityChecker Info: There are no requests to check. 
2016/05/02 17:51:22.759 PlexRequests.Services.PlexAvailabilityChecker Info: There are no requests to check. 
2016/05/02 18:01:22.866 PlexRequests.Services.PlexAvailabilityChecker Info: There are no requests to check. 
2016/05/02 18:11:22.799 PlexRequests.Services.PlexAvailabilityChecker Info: There are no requests to check. 
```
PlexRequests.US has stopped working:
Problem signature:
Problem Event Name: CLR20r3
Problem Signature 01: PlexRequests.exe
Problem Signature 02: 1.6.274.0
Problem Signature 03: 57124338
Problem Signature 04: RestSharp
Problem Signature 05: 105.2.3.0
Problem Signature 06: 55de4cc6
Problem Signature 07: 12f
Problem Signature 08: 7
Problem Signature 09: System.ApplicationException
OS Version: 6.3.9600.2.0.0.272.7
Locale ID: 1033
Additional Information 1: 5861
Additional Information 2: 5861822e1919d7c014bbb064c64908b2
Additional Information 3: 1318
Additional Information 4: 13181ae637ac2592fac0ca2dd662cdcc
And here is the CMD Window output:
Version: 1.6.1
Location of the database: C:\PlexRequests\Release\PlexRequests.sqlite
Request Plex is running on the following: http://+:3000/
Press any key to exit
Unhandled Exception: System.ApplicationException: Error retrieving response. Che
ck inner details for more info. ---> System.InvalidCastException: Unable to cast
object of type 'RestSharp.JsonArray' to type 'System.Collections.Generic.IDicti
onary
2[System.String,System.Object]'.
   at RestSharp.Deserializers.JsonDeserializer.CreateAndMap(Type type, Object element)
   at RestSharp.Deserializers.JsonDeserializer.ConvertValue(Type type, Object value)
   at RestSharp.Deserializers.JsonDeserializer.Map(Object target, IDictionary
2data)
at RestSharp.Deserializers.JsonDeserializer.CreateAndMap(Type type, Object element)
at RestSharp.Deserializers.JsonDeserializer.ConvertValue(Type type, Object value)
at RestSharp.Deserializers.JsonDeserializer.Map(Object target, IDictionary
2data)
   at RestSharp.Deserializers.JsonDeserializer.CreateAndMap(Type type, Object element)
   at RestSharp.Deserializers.JsonDeserializer.ConvertValue(Type type, Object value)
   at RestSharp.Deserializers.JsonDeserializer.BuildList(Type type, Object parent)
   at RestSharp.Deserializers.JsonDeserializer.ConvertValue(Type type, Object value)
   at RestSharp.Deserializers.JsonDeserializer.Map(Object target, IDictionary
2data)
at RestSharp.Deserializers.JsonDeserializer.CreateAndMap(Type type, Object element)
at RestSharp.Deserializers.JsonDeserializer.ConvertValue(Type type, Object value)
at RestSharp.Deserializers.JsonDeserializer.Deserialize[T](IRestResponse response)
at RestSharp.RestClient.Deserialize[T](IRestRequest request, IRestResponse raw)
--- End of inner exception stack trace ---
at PlexRequests.Api.ApiRequest.Execute[T](IRestRequest request, Uri baseUri)
in C:\projects\requestplex\PlexRequests.Api\ApiRequest.cs:line 69
at PlexRequests.Api.CouchPotatoApi.GetMovies(Uri baseUrl, String apiKey, Stri
ng[] status) in C:\projects\requestplex\PlexRequests.Api\CouchPotatoApi.cs:line 125
at PlexRequests.Services.CouchPotatoCacher.Queued(Int64 check) in C:\projects
\requestplex\PlexRequests.Services\CouchPotatoCacher.cs:line 64
at System.Reactive.AnonymousSafeObserver
1.OnNext(T value)
   at System.Reactive.Linq.ObservableImpl.Timer.TimerImpl.Tick(Int64 count)
   at System.Reactive.Concurrency.DefaultScheduler.<>c__DisplayClass9
1.b__7()
at System.Reactive.Concurrency.AsyncLock.Wait(Action action)
at System.Reactive.Concurrency.DefaultScheduler.<>c__DisplayClass9`1.b__6()
at System.Reactive.Concurrency.DefaultConcurrencyAbstractionLayer.PeriodicTimer.Tick(Object state)
at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.TimerQueueTimer.CallCallback()
at System.Threading.TimerQueueTimer.Fire()
at System.Threading.TimerQueue.FireQueuedTimerCompletion(Object state)
at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
at System.Threading.ThreadPoolWorkQueue.Dispatch()
at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by zenjabba** [comment]
I'm having the same problem, every few hours it just stops working. I've tried on Unix, and Windows and both of them crash.

Any debug logs I can send?

**Comment by Drewster727** [comment]
@zenjabba you should have a logs folder with log files in there. Send them over and we'll take a look.

**Comment by zenjabba** [comment]
This is all I found, I think I need to change the debug level.

2016/05/03 07:39:50.890 PlexRequests.UI.Program Trace: Getting product version
2016/05/03 07:39:50.915 PlexRequests.UI.Program Info: Version: 1.6.1
2016/05/03 07:39:51.465 PlexRequests.Store.DbConfiguration Trace: Checking DB
2016/05/03 07:39:55.405 PlexRequests.Core.Setup Info: Begin executing GetProfiles call to Sonarr for quality profiles 
2016/05/03 07:39:55.405 PlexRequests.Core.Setup Info: Begin executing GetProfiles call to CouchPotato for quality profiles 
2016/05/03 07:39:55.635 PlexRequests.Core.Setup Info: Finished executing GetProfiles call to Sonarr for quality profiles 
2016/05/03 07:39:55.660 PlexRequests.Core.Setup Info: Finished executing GetProfiles call to CouchPotato for quality profiles 
2016/05/03 15:57:44.304 PlexRequests.UI.Program Trace: Getting product version
2016/05/03 15:57:44.319 PlexRequests.UI.Program Info: Version: 1.6.1
2016/05/03 15:57:44.339 PlexRequests.Store.DbConfiguration Trace: Checking DB
2016/05/03 15:57:45.124 PlexRequests.Core.Setup Info: Executing GetSettings call to Sonarr for quality profiles
2016/05/03 15:57:45.134 PlexRequests.Core.Setup Info: Executing GetSettings call to CouchPotato for quality profiles
2016/05/03 15:57:45.554 PlexRequests.Core.Setup Info: Begin executing GetProfiles call to CouchPotato for quality profiles 
2016/05/03 15:57:45.554 PlexRequests.Core.Setup Info: Begin executing GetProfiles call to Sonarr for quality profiles 
2016/05/03 15:57:45.699 PlexRequests.Core.Setup Info: Finished executing GetProfiles call to Sonarr for quality profiles 
2016/05/03 15:57:45.699 PlexRequests.Core.Setup Info: Finished executing GetProfiles call to CouchPotato for quality profiles

**Comment by zenjabba** [comment]
Unhandled Exception: System.ApplicationException: Error retrieving response. Che
ck inner details for more info. ---> System.Net.WebException: Unable to connect
to the remote server ---> System.Net.Sockets.SocketException: A connection attem
pt failed because the connected party did not properly respond after a period of
 time, or established connection failed because connected host has failed to res
pond 10.0.0.1:32400
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddre
ss socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Sock
et s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state,
IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at RestSharp.Http.GetRawResponse(HttpWebRequest request)
   at RestSharp.Http.GetResponse(HttpWebRequest request)
   --- End of inner exception stack trace ---
   at PlexRequests.Api.ApiRequest.ExecuteXml[T](IRestRequest request, Uri baseUr
i) in C:\projects\requestplex\PlexRequests.Api\ApiRequest.cs:line 99
   at PlexRequests.Api.PlexApi.GetLibrary(String authToken, Uri plexFullHost, St
ring libraryId) in C:\projects\requestplex\PlexRequests.Api\PlexApi.cs:line 167
   at PlexRequests.Services.PlexAvailabilityChecker.GetLibraries(AuthenticationS
ettings authSettings, PlexSettings plexSettings) in C:\projects\requestplex\Plex
Requests.Services\PlexAvailabilityChecker.cs:line 275
   at PlexRequests.Services.PlexAvailabilityChecker.CachedLibraries(Authenticati
onSettings authSettings, PlexSettings plexSettings, Boolean setCache) in C:\proj
ects\requestplex\PlexRequests.Services\PlexAvailabilityChecker.cs:line 254
   at PlexRequests.Services.PlexAvailabilityChecker.CheckAndUpdateAll(Int64 chec
k) in C:\projects\requestplex\PlexRequests.Services\PlexAvailabilityChecker.cs:l
ine 76
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   at System.Reactive.Linq.ObservableImpl.Timer.TimerImpl.Tick(Int64 count)
   at System.Reactive.Concurrency.DefaultScheduler.<>c__DisplayClass9`1.<Schedul
ePeriodic>b__7()
   at System.Reactive.Concurrency.AsyncLock.Wait(Action action)
   at System.Reactive.Concurrency.DefaultScheduler.<>c__DisplayClass9`1.<Schedul
ePeriodic>b__6()
   at System.Reactive.Concurrency.DefaultConcurrencyAbstractionLayer.PeriodicTim
er.Tick(Object state)
   at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback()

Seems when Plex gets rebooted, it crashes.

**Comment by williamray507** [comment]
Mine will crash even if plex is not restarted, it seems to just crash randomly after a few hours.

**Comment by zenjabba** [comment]
Agreed re: crashing every few hours, but at least I figured out one of the crashes!

**Comment by Drewster727** [comment]
I found that when I had my logging set to "Trace" (or maybe anything below "Info") it will crash after a few hours. Can you guys confirm this?

**Comment by zenjabba** [comment]
Basically it seems my issues are when a service doesn't respond back fast enough, it crashes.


Unhandled Exception: System.ApplicationException: Error retrieving response. Che
ck inner details for more info. ---> System.Net.WebException: The operation has
timed out
   at System.Net.HttpWebRequest.GetResponse()
   at RestSharp.Http.GetRawResponse(HttpWebRequest request)
   at RestSharp.Http.GetResponse(HttpWebRequest request)
   --- End of inner exception stack trace ---
   at PlexRequests.Api.ApiRequest.Execute[T](IRestRequest request, Uri baseUri)
in C:\projects\requestplex\PlexRequests.Api\ApiRequest.cs:line 69
   at PlexRequests.Api.CouchPotatoApi.GetMovies(Uri baseUrl, String apiKey, Stri
ng[] status) in C:\projects\requestplex\PlexRequests.Api\CouchPotatoApi.cs:line
125
   at PlexRequests.Services.CouchPotatoCacher.Queued(Int64 check) in C:\projects
\requestplex\PlexRequests.Services\CouchPotatoCacher.cs:line 64
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   at System.Reactive.Linq.ObservableImpl.Timer.TimerImpl.Tick(Int64 count)
   at System.Reactive.Concurrency.DefaultScheduler.<>c__DisplayClass9`1.<Schedul
ePeriodic>b__7()
   at System.Reactive.Concurrency.AsyncLock.Wait(Action action)
   at System.Reactive.Concurrency.DefaultScheduler.<>c__DisplayClass9`1.<Schedul
ePeriodic>b__6()
   at System.Reactive.Concurrency.DefaultConcurrencyAbstractionLayer.PeriodicTim
er.Tick(Object state)
   at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireQueuedTimerCompletion(Object state)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWor
kItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by zenjabba** [comment]
@Drewster727 What do you consider massive size of plex?

**Comment by tidusjar** [comment]
@Drewster727 can we add some more protective code around the cache services?

**Comment by heartisall** [comment]
Yep mine is crashing all the time too, currently just have a scheduled task to close it and reopen it every few hours. It works, but it's a sloppy workaround.

**Comment by tidusjar** [comment]
Hmm that's not great. We need to know the areas it's crashing so we can stop it. 

It's difficult to code for every error scenario, everyone's setups are different unfortunately. But we can try our best so thank you guys for your patience. 

I'm currently on vacation but I'll see if I can do something when I get back to the hotel tonight. 

Has anyone tried out the latest Dev build because I know we fixed a few crashes around the scheduler.

**Comment by zenjabba** [comment]
If your on Vacation, STAY on vacation!

Seriously this isn’t that important compared to holidays!

**Comment by heartisall** [comment]
I agree completely with @zenjabba enjoy your Vacay man None of this is life threatening.

**Comment by tidusjar** [comment]
Haha thanks guys! I find it difficult as I don't want to disappoint!

**Comment by zenjabba** [comment]
Get back on Vacation and stop reading until your finished. 

Hell my partner would KILL me if I worked on a open source project whilst on Vacation. Nope, this can wait till you get back.

**Comment by zenjabba** [comment]
I've found a way around the problem for now (Under WIndows)

https://www.raymond.cc/blog/disable-program-has-stopped-working-error-dialog-in-windows-server-2008/

Follow this, then I simply created a batch file (below), and created a shortcut to that batch file and placed that short cut into the startup folder. Once it crashes, it drops out, and starts up again :)

plexrqrun.bat
---

@echo off
:start
cd \prexrequest
plexrequest.exe
goto start

**Comment by williamray507** [comment]
Thank you for that.

**Comment by EddiYo** [comment]
Having the same issues on 2012 r2. But @zenjabba workaround works for now. :)

**Comment by tidusjar** [comment]
So, I think i've fixed this on the plane (Need to check it all in).

I'll be verifying it all later.

**Comment by moonjazzz** [comment]
I am actually having this same issue with version 1.10.1. After about 10 minutes the program just crashes.

**Comment by tidusjar** [comment]
@moonjazzz can you open a new issue please?

**Comment by moonjazzz** [comment]
@tidusjar of course, sorry I am new to github :P
