### ISSUE TITLE
500 - InternalServerError  Nancy.RequestExecutionException: Oh noes

### ISSUE THREAD

**Issue by whitecollar17** [tidusjar/PlexRequests.Net#206]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
v1.6.1

#### Operating System:
Windows 10 pro 64bit

#### Mono Version:
x

#### Applicable Logs (from `/logs/` directory or the Admin page):
2016/05/05 00:21:32.767 PlexRequests.UI.Program Trace: Getting product version
2016/05/05 00:21:32.783 PlexRequests.UI.Program Info: Version: 1.6.1
2016/05/05 00:21:32.783 PlexRequests.Store.DbConfiguration Trace: Checking DB
2016/05/05 00:21:33.517 PlexRequests.Core.Setup Info: Executing GetSettings call to CouchPotato for quality profiles
2016/05/05 00:21:33.517 PlexRequests.Core.Setup Info: Executing GetSettings call to Sonarr for quality profiles
2016/05/05 00:21:34.470 PlexRequests.Services.PlexAvailabilityChecker Warn: A setting is null, Ensure Plex is configured correctly, and we have a Plex Auth token. 
2016/05/05 00:21:34.486 PlexRequests.Services.PlexAvailabilityChecker Info: Validation of the plex settings failed. 
Logs go here (Please make sure you remove any personal information from the logs)

Getting a webpage error:
500 - InternalServerError
Something went horribly, horribly wrong while servicing your request.

We're sorry :-(

Error Details

Nancy.RequestExecutionException: Oh noes! ---> Nancy.ViewEngines.ViewNotFoundException: Unable to locate view 'Index'
Currently available view engine extensions: sshtml,html,htm
Locations inspected: views/userlogin/UserLogin/Index-nl-NL,views/userlogin/UserLogin/Index,userlogin/UserLogin/Index-nl-NL,userlogin/UserLogin/Index,views/userlogin/Index-nl-NL,views/userlogin/Index,userlogin/Index-nl-NL,userlogin/Index,views/UserLogin/Index-nl-NL,views/UserLogin/Index,UserLogin/Index-nl-NL,UserLogin/Index,views/Index-nl-NL,views/Index,Index-nl-NL,Index
Root path: C:\plexrequests nieuw\Release\
If you were expecting raw data back, make sure you set the 'Accept'-header of the request to correct format, for example 'application/json'
   at Nancy.ViewEngines.DefaultViewFactory.GetRenderedView(String viewName, Object model, ViewLocationContext viewLocationContext)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at Nancy.ViewEngines.DefaultViewFactory.RenderView(String viewName, Object model, ViewLocationContext viewLocationContext)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at Nancy.Responses.Negotiation.ViewProcessor.Process(MediaRange requestedMediaRange, Object model, NancyContext context)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at Nancy.Responses.Negotiation.DefaultResponseNegotiator.NegotiateResponse(IEnumerable`1 compatibleHeaders, NegotiationContext negotiationContext, NancyContext context)
   at Nancy.Responses.Negotiation.DefaultResponseNegotiator.CreateResponse(IList`1 compatibleHeaders, NegotiationContext negotiationContext, NancyContext context)
   at Nancy.Responses.Negotiation.DefaultResponseNegotiator.NegotiateResponse(Object routeResult, NancyContext context)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at Nancy.Routing.DefaultRouteInvoker.<>c__DisplayClassa.b__6(Task`1 completedTask)
   --- End of inner exception stack trace ---
   at Nancy.NancyEngine.InvokeOnErrorHook(NancyContext context, ErrorPipeline pipeline, Exception ex)

#### Reproduction Steps:

After starting up and try to go the webpage i get this error

**Comment by tidusjar** [comment]
Hi!

You need to follow the install instructions ;)

Unblock the .zip and then extract it! :)
