### ISSUE TITLE
Just download PlexRequests and it crashes on startup 

### ISSUE THREAD

**Issue by enaba** [tidusjar/PlexRequests.Net#274]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
PlexRequests v1.7.4

#### Operating System:
Windows 10

#### Mono Version:
No Idea what is that 

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
2016/05/27 00:14:13.514 PlexRequests.UI.Program Trace: Getting product version
2016/05/27 00:14:13.530 PlexRequests.UI.Program Info: Version: 1.7.4
2016/05/27 00:14:13.631 PlexRequests.Store.DbConfiguration Trace: Checking DB
2016/05/27 00:14:13.646 PlexRequests.Store.DbConfiguration Trace: DB doesn't exist, creating a new one
2016/05/27 00:14:16.344 PlexRequests.Core.Setup Info: Executing GetSettings call to CouchPotato for quality profiles
2016/05/27 00:14:16.344 PlexRequests.Core.Setup Info: Executing GetSettings call to Sonarr for quality profiles
2016/05/27 00:14:16.533 PlexRequests.UI.Program Trace: Getting startup Port 
2016/05/27 00:14:17.115 PlexRequests.UI.Program Trace: Port: 0 
2016/05/27 00:14:20.343 PlexRequests.Services.Jobs.SickRageCacher Trace: Getting the settings 
2016/05/27 00:14:20.343 PlexRequests.Services.Jobs.SonarrCacher Trace: Getting the settings 
2016/05/27 00:14:20.343 PlexRequests.Services.Jobs.StoreBackup Trace: Starting DB Backup 
2016/05/27 00:14:20.321 PlexRequests.Services.Jobs.CouchPotatoCacher Trace: Getting the settings 
2016/05/27 00:14:20.396 PlexRequests.Services.Jobs.PlexAvailabilityChecker Trace: Getting the settings 
2016/05/27 00:14:20.505 PlexRequests.UI.Program Fatal: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.HttpListenerException: Access is denied
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at Microsoft.Owin.Host.HttpListener.OwinHttpListener.Start(HttpListener listener, Func`2 appFunc, IList`1 addresses, IDictionary`2 capabilities, Func`2 loggerFactory)
   at Microsoft.Owin.Host.HttpListener.OwinServerFactory.Create(Func`2 app, IDictionary`2 properties)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Owin.Hosting.ServerFactory.ServerFactoryAdapter.Create(IAppBuilder builder)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.StartServer(StartContext context)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
   at Microsoft.Owin.Hosting.Starter.DirectHostingStarter.Start(StartOptions options)
   at Microsoft.Owin.Hosting.Starter.HostingStarter.Start(StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.StartImplementation(IServiceProvider services, StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.Start(StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.Start[TStartup](StartOptions options)
   at PlexRequests.UI.Program.Main(String[] args) in C:\projects\requestplex\PlexRequests.UI\Program.cs:line 84 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.HttpListenerException: Access is denied
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at Microsoft.Owin.Host.HttpListener.OwinHttpListener.Start(HttpListener listener, Func`2 appFunc, IList`1 addresses, IDictionary`2 capabilities, Func`2 loggerFactory)
   at Microsoft.Owin.Host.HttpListener.OwinServerFactory.Create(Func`2 app, IDictionary`2 properties)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Owin.Hosting.ServerFactory.ServerFactoryAdapter.Create(IAppBuilder builder)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.StartServer(StartContext context)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
   at Microsoft.Owin.Hosting.Starter.DirectHostingStarter.Start(StartOptions options)
   at Microsoft.Owin.Hosting.Starter.HostingStarter.Start(StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.StartImplementation(IServiceProvider services, StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.Start(StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.Start[TStartup](StartOptions options)
   at PlexRequests.UI.Program.Main(String[] args) in C:\projects\requestplex\PlexRequests.UI\Program.cs:line 84
2016/05/27 00:14:21.238 PlexRequests.Services.Jobs.PlexAvailabilityChecker Trace: Getting all the requests 
2016/05/27 00:14:21.502 PlexRequests.Services.Jobs.PlexAvailabilityChecker Warn: A setting is null, Ensure Plex is configured correctly, and we have a Plex Auth token. 
2016/05/27 00:14:21.603 PlexRequests.Services.Jobs.PlexAvailabilityChecker Info: Validation of the plex settings failed. 
2016/05/27 00:14:21.975 PlexRequests.Services.Jobs.StoreBackup Trace: Starting DB Cleanup 
2016/05/27 00:14:34.416 PlexRequests.UI.Program Trace: Getting product version
2016/05/27 00:14:34.432 PlexRequests.UI.Program Info: Version: 1.7.4
2016/05/27 00:14:34.432 PlexRequests.Store.DbConfiguration Trace: Checking DB
2016/05/27 00:14:34.617 PlexRequests.Core.Setup Info: Executing GetSettings call to CouchPotato for quality profiles
2016/05/27 00:14:34.617 PlexRequests.Core.Setup Info: Executing GetSettings call to Sonarr for quality profiles
2016/05/27 00:14:34.715 PlexRequests.UI.Program Trace: Getting startup Port 
2016/05/27 00:14:35.078 PlexRequests.UI.Program Trace: Port: 0 
2016/05/27 00:14:36.945 PlexRequests.UI.Program Fatal: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.HttpListenerException: Access is denied
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at Microsoft.Owin.Host.HttpListener.OwinHttpListener.Start(HttpListener listener, Func`2 appFunc, IList`1 addresses, IDictionary`2 capabilities, Func`2 loggerFactory)
   at Microsoft.Owin.Host.HttpListener.OwinServerFactory.Create(Func`2 app, IDictionary`2 properties)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Owin.Hosting.ServerFactory.ServerFactoryAdapter.Create(IAppBuilder builder)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.StartServer(StartContext context)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
   at Microsoft.Owin.Hosting.Starter.DirectHostingStarter.Start(StartOptions options)
   at Microsoft.Owin.Hosting.Starter.HostingStarter.Start(StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.StartImplementation(IServiceProvider services, StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.Start(StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.Start[TStartup](StartOptions options)
   at PlexRequests.UI.Program.Main(String[] args) in C:\projects\requestplex\PlexRequests.UI\Program.cs:line 84 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.HttpListenerException: Access is denied
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at Microsoft.Owin.Host.HttpListener.OwinHttpListener.Start(HttpListener listener, Func`2 appFunc, IList`1 addresses, IDictionary`2 capabilities, Func`2 loggerFactory)
   at Microsoft.Owin.Host.HttpListener.OwinServerFactory.Create(Func`2 app, IDictionary`2 properties)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Owin.Hosting.ServerFactory.ServerFactoryAdapter.Create(IAppBuilder builder)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.StartServer(StartContext context)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
   at Microsoft.Owin.Hosting.Starter.DirectHostingStarter.Start(StartOptions options)
   at Microsoft.Owin.Hosting.Starter.HostingStarter.Start(StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.StartImplementation(IServiceProvider services, StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.Start(StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.Start[TStartup](StartOptions options)
   at PlexRequests.UI.Program.Main(String[] args) in C:\projects\requestplex\PlexRequests.UI\Program.cs:line 84
2016/05/27 00:14:36.964 PlexRequests.Services.Jobs.SonarrCacher Trace: Getting the settings 
2016/05/27 00:14:36.964 PlexRequests.Services.Jobs.CouchPotatoCacher Trace: Getting the settings 
2016/05/27 00:14:36.964 PlexRequests.Services.Jobs.PlexAvailabilityChecker Trace: Getting the settings 
2016/05/27 00:14:36.964 PlexRequests.Services.Jobs.StoreBackup Trace: Starting DB Backup 
2016/05/27 00:16:13.692 PlexRequests.UI.Program Trace: Getting product version
2016/05/27 00:16:13.692 PlexRequests.UI.Program Info: Version: 1.7.4
2016/05/27 00:16:13.709 PlexRequests.Store.DbConfiguration Trace: Checking DB
2016/05/27 00:16:13.877 PlexRequests.Core.Setup Info: Executing GetSettings call to CouchPotato for quality profiles
2016/05/27 00:16:13.877 PlexRequests.Core.Setup Info: Executing GetSettings call to Sonarr for quality profiles
2016/05/27 00:16:13.977 PlexRequests.UI.Program Trace: Getting startup Port 
2016/05/27 00:16:14.316 PlexRequests.UI.Program Trace: Port: 0 
2016/05/27 00:16:16.504 PlexRequests.UI.Program Fatal: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.HttpListenerException: Access is denied
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at Microsoft.Owin.Host.HttpListener.OwinHttpListener.Start(HttpListener listener, Func`2 appFunc, IList`1 addresses, IDictionary`2 capabilities, Func`2 loggerFactory)
   at Microsoft.Owin.Host.HttpListener.OwinServerFactory.Create(Func`2 app, IDictionary`2 properties)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Owin.Hosting.ServerFactory.ServerFactoryAdapter.Create(IAppBuilder builder)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.StartServer(StartContext context)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
   at Microsoft.Owin.Hosting.Starter.DirectHostingStarter.Start(StartOptions options)
   at Microsoft.Owin.Hosting.Starter.HostingStarter.Start(StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.StartImplementation(IServiceProvider services, StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.Start(StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.Start[TStartup](StartOptions options)
   at PlexRequests.UI.Program.Main(String[] args) in C:\projects\requestplex\PlexRequests.UI\Program.cs:line 84 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.HttpListenerException: Access is denied
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at Microsoft.Owin.Host.HttpListener.OwinHttpListener.Start(HttpListener listener, Func`2 appFunc, IList`1 addresses, IDictionary`2 capabilities, Func`2 loggerFactory)
   at Microsoft.Owin.Host.HttpListener.OwinServerFactory.Create(Func`2 app, IDictionary`2 properties)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Owin.Hosting.ServerFactory.ServerFactoryAdapter.Create(IAppBuilder builder)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.StartServer(StartContext context)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
   at Microsoft.Owin.Hosting.Starter.DirectHostingStarter.Start(StartOptions options)
```

#### Reproduction Steps:

Just download and i go the folder \Release then run PlexRequests

**Comment by tidusjar** [comment]
You need to run as admin.

**Comment by enaba** [comment]
It Finished, Its saying Plex request is now ready.

How do i open it now ?

**Comment by tidusjar** [comment]
http://localhost:3579

It does say it in the console window.

**Comment by enaba** [comment]
I'm so sorry Tidusjar, now its giving me this error 

Error Details

Nancy.RequestExecutionException: Oh noes! ---> Nancy.ViewEngines.ViewNotFoundException: Unable to locate view 'Index'
Currently available view engine extensions: sshtml,html,htm
Locations inspected: views/userlogin/UserLogin/Index-en-US,views/userlogin/UserLogin/Index,userlogin/UserLogin/Index-en-US,userlogin/UserLogin/Index,views/userlogin/Index-en-US,views/userlogin/Index,userlogin/Index-en-US,userlogin/Index,views/UserLogin/Index-en-US,views/UserLogin/Index,UserLogin/Index-en-US,UserLogin/Index,views/Index-en-US,views/Index,Index-en-US,Index
Root path: C:\PlexRequests\Release\
If you were expecting raw data back, make sure you set the 'Accept'-header of the request to correct format, for example 'application/json'
   at Nancy.ViewEngines.DefaultViewFactory.GetRenderedView(String viewName, Object model, ViewLocationContext viewLocationContext)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at CallSite.Target(Closure , CallSite , DefaultViewFactory , Object , Object , ViewLocationContext )
   at Nancy.ViewEngines.DefaultViewFactory.RenderView(String viewName, Object model, ViewLocationContext viewLocationContext)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at CallSite.Target(Closure , CallSite , IViewFactory , String , Object , ViewLocationContext )
   at Nancy.Responses.Negotiation.ViewProcessor.Process(MediaRange requestedMediaRange, Object model, NancyContext context)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at CallSite.Target(Closure , CallSite , IResponseProcessor , String , Object , NancyContext )
   at Nancy.Responses.Negotiation.DefaultResponseNegotiator.NegotiateResponse(IEnumerable`1 compatibleHeaders, NegotiationContext negotiationContext, NancyContext context)
   at Nancy.Responses.Negotiation.DefaultResponseNegotiator.CreateResponse(IList`1 compatibleHeaders, NegotiationContext negotiationContext, NancyContext context)
   at Nancy.Responses.Negotiation.DefaultResponseNegotiator.NegotiateResponse(Object routeResult, NancyContext context)
   at Nancy.Routing.DefaultRouteInvoker.<>c__DisplayClassa.b__6(Task`1 completedTask)
   --- End of inner exception stack trace ---
   at Nancy.NancyEngine.InvokeOnErrorHook(NancyContext context, ErrorPipeline pipeline, Exception ex)

**Comment by tidusjar** [comment]
It's ok! 

There are instructions in the readme. You need to Unblock the `.zip` file and then extract it. Windows likes to block `.dll's` from .zip files on Github.

**Comment by enaba** [comment]
Wow its working, bless you.

so sorry for the trouble

**Comment by tidusjar** [comment]
Not a problem, Get any more issues let me know :+1:

**Comment by enaba** [comment]
tidusjar if you don't mind me asking, how do i not give my family assess on that, do i give them a website or something ?

**Comment by tidusjar** [comment]
So your family needs to access the Plex Requests website. You can do this by port forwarding etc.

If you enable authentication (In the settings) your family members will need a Plex account to log in. 

So if you are going to open up Plex Requests to the internet, I suggest that you enable Authentication otherwise anyone can access it and request things.

**Comment by enaba** [comment]
I think this is more than i can bite at this point, i did enable Authentication.

But not sure what is the address they need to type

**Comment by tidusjar** [comment]
Your going to need to lookup port forwarding and get a DDNS. 

Your family can type in the DDNS name then. 

Just some light Googling :D. 

Or if your family are on your network then they can access it by the IP address and port (make sure you open up the firewall, check the wiki).

**Comment by enaba** [comment]
thanks tidusjar, I wish this would be an integrated part of plex in the future.

It would really be amazing. thank you so much for your great effort making this and your amazing support

**Comment by tidusjar** [comment]
That would be nice!!

Not a problem. 

Jamie.
