### ISSUE TITLE
Headphones - 500 Internal Server Error in Logs after requesting album

### ISSUE THREAD

**Issue by domenicdistefano** [tidusjar/PlexRequests.Net#320]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
1.7.5

#### Operating System:
Unbuntu 14.04

#### Mono Version:
4.2.3

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

Queue Result: { "Request": { "AlwaysMultipartFormData": false, "JsonSerializer": { "DateFormat": null, "RootElement": null, "Namespace": null, "ContentType": "application/json" }, "XmlSerializer": { "RootElement": null, "Namespace": null, "DateFormat": null, "ContentType": "text/xml" }, "ResponseWriter": null, "UseDefaultCredentials": false, "Parameters": [ { "Name": "apikey", "Value": "55ee8e5c435f8f3853732475696336c6", "Type": 5, "ContentType": null }, { "Name": "albumId", "Value": "959272f9-97ae-4179-aebe-950eef64ed93", "Type": 2, "ContentType": null }, { "Name": "Accept", "Value": "application/json, application/xml, text/json, text/x-json, text/javascript, text/xml", "Type": 3, "ContentType": null } ], "Files": [], "Method": 0, "Resource": "/api?cmd=queueAlbum&id={albumId}", "RequestFormat": 1, "RootElement": null, "OnBeforeDeserialization": { "Delegate": { "delegateEntry": null }, "method0": { "Name": "<.ctor>b__0", "AssemblyName": "RestSharp, Version=105.2.3.0, Culture=neutral, PublicKeyToken=null", "ClassName": "RestSharp.RestRequest", "Signature": "Void <.ctor>b__0(RestSharp.IRestResponse)", "Signature2": "System.Void <.ctor>b__0(RestSharp.IRestResponse)", "MemberType": 8, "GenericArguments": null } }, "DateFormat": null, "XmlNamespace": null, "Credentials": null, "UserState": null, "Timeout": 0, "ReadWriteTimeout": 0, "Attempts": 1 }, "ContentType": "text/html;charset=utf-8", "ContentLength": 1959, "ContentEncoding": "", "Content": "\n\n\n \n \n \n\n \n
500 Internal Server Error
\n
The server encountered an unexpected condition which prevented it from fulfilling the request.

\n
Traceback (most recent call last):\n  File \"lib/cherrypy/_cprequest.py\", line 670, in respond\n    response.body = self.handler()\n  File \"lib/cherrypy/lib/encoding.py\", line 217, in __call__\n    self.body = self.oldhandler(*args, **kwargs)\n  File \"lib/cherrypy/_cpdispatch.py\", line 61, in __call__\n    return self.callable(*self.args, **self.kwargs)\n  File \"/opt/headphones/headphones/webserve.py\", line 1603, in api\n    return a.fetchData()\n  File \"/opt/headphones/headphones/api.py\", line 87, in fetchData\n    methodToCall(**self.kwargs)\n  File \"/opt/headphones/headphones/api.py\", line 316, in _queueAlbum\n    searcher.searchforalbum(self.id, new)\n  File \"/opt/headphones/headphones/searcher.py\", line 233, in searchforalbum\n    do_sorted_search(album, new, losslessOnly)\n  File \"/opt/headphones/headphones/searcher.py\", line 266, in do_sorted_search\n    results = searchNZB(album, new, losslessOnly, albumlength)\n  File \"/opt/headphones/headphones/searcher.py\", line 499, in searchNZB\n    if album['ArtistName'] in album['AlbumTitle'] or len(album['ArtistName']) < 4 or len(\nTypeError: argument of type 'NoneType' is not iterable\n
\n
\n \n Powered by CherryPy 3.6.0\n \n
\n \n\n", "StatusCode": 500, "StatusDescription": "Internal Server Error", "RawBytes": "PCFET0NUWVBFIGh0bWwgUFVCTElDCiItLy9XM0MvL0RURCBYSFRNTCAxLjAgVHJhbnNpdGlvbmFsLy9FTiIKImh0dHA6Ly93d3cudzMub3JnL1RSL3hodG1sMS9EVEQveGh0bWwxLXRyYW5zaXRpb25hbC5kdGQiPgo8aHRtbD4KPGhlYWQ+CiAgICA8bWV0YSBodHRwLWVxdWl2PSJDb250ZW50LVR5cGUiIGNvbnRlbnQ9InRleHQvaHRtbDsgY2hhcnNldD11dGYtOCI+PC9tZXRhPgogICAgPHRpdGxlPjUwMCBJbnRlcm5hbCBTZXJ2ZXIgRXJyb3I8L3RpdGxlPgogICAgPHN0eWxlIHR5cGU9InRleHQvY3NzIj4KICAgICNwb3dlcmVkX2J5IHsKICAgICAgICBtYXJnaW4tdG9wOiAyMHB4OwogICAgICAgIGJvcmRlci10b3A6IDJweCBzb2xpZCBibGFjazsKICAgICAgICBmb250LXN0eWxlOiBpdGFsaWM7CiAgICB9CgogICAgI3RyYWNlYmFjayB7CiAgICAgICAgY29sb3I6IHJlZDsKICAgIH0KICAgIDwvc3R5bGU+CjwvaGVhZD4KICAgIDxib2R5PgogICAgICAgIDxoMj41MDAgSW50ZXJuYWwgU2VydmVyIEVycm9yPC9oMj4KICAgICAgICA8cD5UaGUgc2VydmVyIGVuY291bnRlcmVkIGFuIHVuZXhwZWN0ZWQgY29uZGl0aW9uIHdoaWNoIHByZXZlbnRlZCBpdCBmcm9tIGZ1bGZpbGxpbmcgdGhlIHJlcXVlc3QuPC9wPgogICAgICAgIDxwcmUgaWQ9InRyYWNlYmFjayI+VHJhY2ViYWNrIChtb3N0IHJlY2VudCBjYWxsIGxhc3QpOgogIEZpbGUgImxpYi9jaGVycnlweS9fY3ByZXF1ZXN0LnB5IiwgbGluZSA2NzAsIGluIHJlc3BvbmQKICAgIHJlc3BvbnNlLmJvZHkgPSBzZWxmLmhhbmRsZXIoKQogIEZpbGUgImxpYi9jaGVycnlweS9saWIvZW5jb2RpbmcucHkiLCBsaW5lIDIxNywgaW4gX19jYWxsX18KICAgIHNlbGYuYm9keSA9IHNlbGYub2xkaGFuZGxlcigqYXJncywgKiprd2FyZ3MpCiAgRmlsZSAibGliL2NoZXJyeXB5L19jcGRpc3BhdGNoLnB5IiwgbGluZSA2MSwgaW4gX19jYWxsX18KICAgIHJldHVybiBzZWxmLmNhbGxhYmxlKCpzZWxmLmFyZ3MsICoqc2VsZi5rd2FyZ3MpCiAgRmlsZSAiL29wdC9oZWFkcGhvbmVzL2hlYWRwaG9uZXMvd2Vic2VydmUucHkiLCBsaW5lIDE2MDMsIGluIGFwaQogICAgcmV0dXJuIGEuZmV0Y2hEYXRhKCkKICBGaWxlICIvb3B0L2hlYWRwaG9uZXMvaGVhZHBob25lcy9hcGkucHkiLCBsaW5lIDg3LCBpbiBmZXRjaERhdGEKICAgIG1ldGhvZFRvQ2FsbCgqKnNlbGYua3dhcmdzKQogIEZpbGUgIi9vcHQvaGVhZHBob25lcy9oZWFkcGhvbmVzL2FwaS5weSIsIGxpbmUgMzE2LCBpbiBfcXVldWVBbGJ1bQogICAgc2VhcmNoZXIuc2VhcmNoZm9yYWxidW0oc2VsZi5pZCwgbmV3KQogIEZpbGUgIi9vcHQvaGVhZHBob25lcy9oZWFkcGhvbmVzL3NlYXJjaGVyLnB5IiwgbGluZSAyMzMsIGluIHNlYXJjaGZvcmFsYnVtCiAgICBkb19zb3J0ZWRfc2VhcmNoKGFsYnVtLCBuZXcsIGxvc3NsZXNzT25seSkKICBGaWxlICIvb3B0L2hlYWRwaG9uZXMvaGVhZHBob25lcy9zZWFyY2hlci5weSIsIGxpbmUgMjY2LCBpbiBkb19zb3J0ZWRfc2VhcmNoCiAgICByZXN1bHRzID0gc2VhcmNoTlpCKGFsYnVtLCBuZXcsIGxvc3NsZXNzT25seSwgYWxidW1sZW5ndGgpCiAgRmlsZSAiL29wdC9oZWFkcGhvbmVzL2hlYWRwaG9uZXMvc2VhcmNoZXIucHkiLCBsaW5lIDQ5OSwgaW4gc2VhcmNoTlpCCiAgICBpZiBhbGJ1bVsnQXJ0aXN0TmFtZSddIGluIGFsYnVtWydBbGJ1bVRpdGxlJ10gb3IgbGVuKGFsYnVtWydBcnRpc3ROYW1lJ10pICZsdDsgNCBvciBsZW4oClR5cGVFcnJvcjogYXJndW1lbnQgb2YgdHlwZSAnTm9uZVR5cGUnIGlzIG5vdCBpdGVyYWJsZQo8L3ByZT4KICAgIDxkaXYgaWQ9InBvd2VyZWRfYnkiPgogICAgICA8c3Bhbj4KICAgICAgICBQb3dlcmVkIGJ5IDxhIGhyZWY9Imh0dHA6Ly93d3cuY2hlcnJ5cHkub3JnIj5DaGVycnlQeSAzLjYuMDwvYT4KICAgICAgPC9zcGFuPgogICAgPC9kaXY+CiAgICA8L2JvZHk+CjwvaHRtbD4K", "ResponseUri": "http://10.10.10.20:8181/api?cmd=queueAlbum&id=959272f9-97ae-4179-aebe-950eef64ed93&apikey=55ee8e5c435f8f3853732475696336c6", "Server": "CherryPy/3.6.0", "Cookies": [], "Headers": [ { "Name": "Date", "Value": "Tue, 14 Jun 2016 01:04:43 GMT", "Type": 3, "ContentType": null }, { "Name": "Content-Length", "Value": "1959", "Type": 3, "ContentType": null }, { "Name": "Content-Type", "Value": "text/html;charset=utf-8", "Type": 3, "ContentType": null }, { "Name": "Server", "Value": "CherryPy/3.6.0", "Type": 3, "ContentType": null } ], "ResponseStatus": 1, "ErrorMessage": null, "ErrorException": null }	PlexRequests.Api.HeadphonesApi	Trace	6/13/2016 8:04:43 PM
Queue Result:
500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "lib/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "lib/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/headphones/headphones/webserve.py", line 1603, in api
    return a.fetchData()
  File "/opt/headphones/headphones/api.py", line 87, in fetchData
    methodToCall(**self.kwargs)
  File "/opt/headphones/headphones/api.py", line 316, in _queueAlbum
    searcher.searchforalbum(self.id, new)
  File "/opt/headphones/headphones/searcher.py", line 233, in searchforalbum
    do_sorted_search(album, new, losslessOnly)
  File "/opt/headphones/headphones/searcher.py", line 266, in do_sorted_search
    results = searchNZB(album, new, losslessOnly, albumlength)
  File "/opt/headphones/headphones/searcher.py", line 499, in searchNZB
    if album['ArtistName'] in album['AlbumTitle'] or len(album['ArtistName']) < 4 or len(
TypeError: argument of type 'NoneType' is not iterable
```

#### Reproduction Steps:

Just try to add an album...

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Seems to be an issue with Headphones, can you check if the Headphones logs?

**Comment by domenicdistefano** [comment]
I will check again this evening but when this happens I get a wanted item as "none" in headphones. Thanks for the help!

**Comment by domenicdistefano** [comment]
I completely built a new windows box and installed Headphones and PlexRequests.net from scratch on the same box. Unfortunately I am getting the same issue. Pasted in below are the logs and some pics of interest.

**Comment by tidusjar** [comment]
This still an issue?

**Comment by DrakeJones** [comment]
Yes, Still an issue.
