### ISSUE TITLE
Sorry for the noob question.  I cannot get the UI to start below are the error logs

### ISSUE THREAD

**Issue by ljhoyt77** [tidusjar/PlexRequests.Net#349]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Logs go here (Please make sure you remove any personal information from the logs)
```

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

2016/06/21 21:02:18.550 PlexRequests.UI.Program Trace: Getting product version
2016/06/21 21:02:18.550 PlexRequests.UI.Program Info: Version: 1.8.1
2016/06/21 21:02:18.606 PlexRequests.Store.DbConfiguration Trace: Checking DB
2016/06/21 21:02:18.606 PlexRequests.Store.DbConfiguration Trace: DB doesn't exist, creating a new one
2016/06/21 21:02:19.672 PlexRequests.Core.Setup Info: Executing GetSettings call to Sonarr for quality profiles
2016/06/21 21:02:19.672 PlexRequests.Core.Setup Info: Executing GetSettings call to CouchPotato for quality profiles
2016/06/21 21:02:19.721 PlexRequests.UI.Program Trace: Getting startup Port 
2016/06/21 21:02:19.888 PlexRequests.UI.Program Trace: Port: 0 
2016/06/21 21:02:22.809 PlexRequests.Services.Jobs.PlexAvailabilityChecker Warn: A setting is null, Ensure Plex is configured correctly, and we have a Plex Auth token. 
2016/06/21 21:02:22.809 PlexRequests.Services.Jobs.CouchPotatoCacher Trace: Getting the settings 
2016/06/21 21:02:22.809 PlexRequests.Services.Jobs.SonarrCacher Trace: Getting the settings 
2016/06/21 21:02:22.809 PlexRequests.Services.Jobs.SickRageCacher Trace: Getting the settings 
2016/06/21 21:02:22.809 PlexRequests.Services.Jobs.StoreBackup Trace: Starting DB Backup 
2016/06/21 21:02:22.829 PlexRequests.Services.Jobs.PlexAvailabilityChecker Debug: Validation of the plex settings failed. 
2016/06/21 21:02:22.844 PlexRequests.UI.Program Info: This is not Mono 
2016/06/21 21:02:22.937 PlexRequests.Services.Jobs.StoreBackup Trace: Starting DB Cleanup 
2016/06/21 21:02:35.123 PlexRequests.UI.Program Trace: Getting product version
2016/06/21 21:02:35.123 PlexRequests.UI.Program Info: Version: 1.8.1
2016/06/21 21:02:35.123 PlexRequests.Store.DbConfiguration Trace: Checking DB
2016/06/21 21:02:35.271 PlexRequests.Core.Setup Info: Executing GetSettings call to CouchPotato for quality profiles
2016/06/21 21:02:35.295 PlexRequests.Core.Setup Info: Executing GetSettings call to Sonarr for quality profiles
2016/06/21 21:02:35.412 PlexRequests.UI.Program Trace: Getting startup Port 
2016/06/21 21:02:35.648 PlexRequests.UI.Program Trace: Port: 0 
2016/06/21 21:02:37.880 PlexRequests.Services.Jobs.SickRageCacher Trace: Getting the settings 
2016/06/21 21:02:37.885 PlexRequests.Services.Jobs.SonarrCacher Trace: Getting the settings 
2016/06/21 21:02:37.885 PlexRequests.Services.Jobs.StoreBackup Trace: Starting DB Backup 
2016/06/21 21:02:37.885 PlexRequests.Services.Jobs.PlexAvailabilityChecker Warn: A setting is null, Ensure Plex is configured correctly, and we have a Plex Auth token. 
2016/06/21 21:02:37.885 PlexRequests.Services.Jobs.CouchPotatoCacher Trace: Getting the settings 
2016/06/21 21:02:37.880 PlexRequests.UI.Program Fatal: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.HttpListenerException: Failed to listen on prefix 'http://+:3579/' because it conflicts with an existing registration on the machine.
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at Microsoft.Owin.Host.HttpListener.OwinHttpListener.Start(HttpListener listener, Func`2 appFunc, IList`1 addresses, IDictionary`2 capabilities, Func`2 loggerFactory)
   at Microsoft.Owin.Host.HttpListener.OwinServerFactory.Create(Func`2 app, IDictionary`2 properties)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Owin.Hosting.ServerFactory.ServerFactoryAdapter.Create(IAppBuilder builder)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.StartServer(StartContext context)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
   at Microsoft.Owin.Hosting.Starter.DirectHostingStarter.Start(StartOptions options)
   at Microsoft.Owin.Hosting.Starter.HostingStarter.Start(StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.StartImplementation(IServiceProvider services, StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.Start(StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.Start[TStartup](StartOptions options)
   at PlexRequests.UI.Program.Main(String[] args) in C:\projects\requestplex\PlexRequests.UI\Program.cs:line 84 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.HttpListenerException: Failed to listen on prefix 'http://+:3579/' because it conflicts with an existing registration on the machine.
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at Microsoft.Owin.Host.HttpListener.OwinHttpListener.Start(HttpListener listener, Func`2 appFunc, IList`1 addresses, IDictionary`2 capabilities, Func`2 loggerFactory)
   at Microsoft.Owin.Host.HttpListener.OwinServerFactory.Create(Func`2 app, IDictionary`2 properties)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Owin.Hosting.ServerFactory.ServerFactoryAdapter.Create(IAppBuilder builder)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.StartServer(StartContext context)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
   at Microsoft.Owin.Hosting.Starter.DirectHostingStarter.Start(StartOptions options)
   at Microsoft.Owin.Hosting.Starter.HostingStarter.Start(StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.StartImplementation(IServiceProvider services, StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.Start(StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.Start[TStartup](StartOptions options)
   at PlexRequests.UI.Program.Main(String[] args) in C:\projects\requestplex\PlexRequests.UI\Program.cs:line 84
2016/06/21 21:02:38.202 PlexRequests.Services.Jobs.PlexAvailabilityChecker Debug: Validation of the plex settings failed. 
2016/06/21 21:02:50.647 PlexRequests.UI.Program Trace: Getting product version
2016/06/21 21:02:50.652 PlexRequests.UI.Program Info: Version: 1.8.1
2016/06/21 21:02:50.652 PlexRequests.Store.DbConfiguration Trace: Checking DB
2016/06/21 21:02:50.796 PlexRequests.Core.Setup Info: Executing GetSettings call to CouchPotato for quality profiles
2016/06/21 21:02:50.819 PlexRequests.Core.Setup Info: Executing GetSettings call to Sonarr for quality profiles
2016/06/21 21:02:50.927 PlexRequests.UI.Program Trace: Getting startup Port 
2016/06/21 21:02:51.162 PlexRequests.UI.Program Trace: Port: 0 
2016/06/21 21:02:53.386 PlexRequests.UI.Program Fatal: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.HttpListenerException: Failed to listen on prefix 'http://+:3579/' because it conflicts with an existing registration on the machine.
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at Microsoft.Owin.Host.HttpListener.OwinHttpListener.Start(HttpListener listener, Func`2 appFunc, IList`1 addresses, IDictionary`2 capabilities, Func`2 loggerFactory)
   at Microsoft.Owin.Host.HttpListener.OwinServerFactory.Create(Func`2 app, IDictionary`2 properties)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Owin.Hosting.ServerFactory.ServerFactoryAdapter.Create(IAppBuilder builder)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.StartServer(StartContext context)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
   at Microsoft.Owin.Hosting.Starter.DirectHostingStarter.Start(StartOptions options)
   at Microsoft.Owin.Hosting.Starter.HostingStarter.Start(StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.StartImplementation(IServiceProvider services, StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.Start(StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.Start[TStartup](StartOptions options)
   at PlexRequests.UI.Program.Main(String[] args) in C:\projects\requestplex\PlexRequests.UI\Program.cs:line 84 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.HttpListenerException: Failed to listen on prefix 'http://+:3579/' because it conflicts with an existing registration on the machine.
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at Microsoft.Owin.Host.HttpListener.OwinHttpListener.Start(HttpListener listener, Func`2 appFunc, IList`1 addresses, IDictionary`2 capabilities, Func`2 loggerFactory)
   at Microsoft.Owin.Host.HttpListener.OwinServerFactory.Create(Func`2 app, IDictionary`2 properties)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Owin.Hosting.ServerFactory.ServerFactoryAdapter.Create(IAppBuilder builder)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.StartServer(StartContext context)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
   at Microsoft.Owin.Hosting.Starter.DirectHostingStarter.Start(StartOptions options)
   at Microsoft.Owin.Hosting.Starter.HostingStarter.Start(StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.StartImplementation(IServiceProvider services, StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.Start(StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.Start[TStartup](StartOptions options)
   at PlexRequests.UI.Program.Main(String[] args) in C:\projects\requestplex\PlexRequests.UI\Program.cs:line 84
2016/06/21 21:02:53.386 PlexRequests.Services.Jobs.PlexAvailabilityChecker Warn: A setting is null, Ensure Plex is configured correctly, and we have a Plex Auth token. 
2016/06/21 21:02:53.386 PlexRequests.Services.Jobs.SickRageCacher Trace: Getting the settings 
2016/06/21 21:02:53.386 PlexRequests.Services.Jobs.CouchPotatoCacher Trace: Getting the settings 
2016/06/21 21:02:53.386 PlexRequests.Services.Jobs.SonarrCacher Trace: Getting the settings 
2016/06/21 21:03:00.877 PlexRequests.UI.Program Trace: Getting product version
2016/06/21 21:03:00.877 PlexRequests.UI.Program Info: Version: 1.8.1
2016/06/21 21:03:00.888 PlexRequests.Store.DbConfiguration Trace: Checking DB
2016/06/21 21:03:01.030 PlexRequests.Core.Setup Info: Executing GetSettings call to CouchPotato for quality profiles
2016/06/21 21:03:01.054 PlexRequests.Core.Setup Info: Executing GetSettings call to Sonarr for quality profiles
2016/06/21 21:03:01.167 PlexRequests.UI.Program Trace: Getting startup Port 
2016/06/21 21:03:01.411 PlexRequests.UI.Program Trace: Port: 0 
2016/06/21 21:03:03.655 PlexRequests.Services.Jobs.SonarrCacher Trace: Getting the settings 
2016/06/21 21:03:03.655 PlexRequests.Services.Jobs.CouchPotatoCacher Trace: Getting the settings 
2016/06/21 21:03:03.655 PlexRequests.UI.Program Fatal: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.HttpListenerException: Failed to listen on prefix 'http://+:3579/' because it conflicts with an existing registration on the machine.
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at Microsoft.Owin.Host.HttpListener.OwinHttpListener.Start(HttpListener listener, Func`2 appFunc, IList`1 addresses, IDictionary`2 capabilities, Func`2 loggerFactory)
   at Microsoft.Owin.Host.HttpListener.OwinServerFactory.Create(Func`2 app, IDictionary`2 properties)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Owin.Hosting.ServerFactory.ServerFactoryAdapter.Create(IAppBuilder builder)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.StartServer(StartContext context)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
   at Microsoft.Owin.Hosting.Starter.DirectHostingStarter.Start(StartOptions options)
   at Microsoft.Owin.Hosting.Starter.HostingStarter.Start(StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.StartImplementation(IServiceProvider services, StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.Start(StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.Start[TStartup](StartOptions options)
   at PlexRequests.UI.Program.Main(String[] args) in C:\projects\requestplex\PlexRequests.UI\Program.cs:line 84 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.HttpListenerException: Failed to listen on prefix 'http://+:3579/' because it conflicts with an existing registration on the machine.
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at Microsoft.Owin.Host.HttpListener.OwinHttpListener.Start(HttpListener listener, Func`2 appFunc, IList`1 addresses, IDictionary`2 capabilities, Func`2 loggerFactory)
   at Microsoft.Owin.Host.HttpListener.OwinServerFactory.Create(Func`2 app, IDictionary`2 properties)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Owin.Hosting.ServerFactory.ServerFactoryAdapter.Create(IAppBuilder builder)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.StartServer(StartContext context)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
   at Microsoft.Owin.Hosting.Starter.DirectHostingStarter.Start(StartOptions options)
   at Microsoft.Owin.Hosting.Starter.HostingStarter.Start(StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.StartImplementation(IServiceProvider services, StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.Start(StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.Start[TStartup](StartOptions options)
   at PlexRequests.UI.Program.Main(String[] args) in C:\projects\requestplex\PlexRequests.UI\Program.cs:line 84
2016/06/21 21:03:03.655 PlexRequests.Services.Jobs.StoreBackup Trace: Starting DB Backup 
2016/06/21 21:03:03.655 PlexRequests.Services.Jobs.SickRageCacher Trace: Getting the settings

**Comment by tedrock** [comment]
I'm not the dev but...
`2016/06/21 21:02:53.386 PlexRequests.UI.Program Fatal: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.HttpListenerException: Failed to listen on prefix 'http://+:3579/' because it conflicts with an existing registration on the machine.`
Makes it seem like something else is listening on or blocking port 3579.
