### ISSUE TITLE
Can't find plex error

### ISSUE THREAD

**Issue by KamakaziSanne** [tidusjar/PlexRequests.Net#576]
PlexRequests.net doesn't see movies and tv shows that are already in my plex library?
I have episode searching on, but get these errors:

```
at PlexRequests.UI.Startup.Configuration(IAppBuilder app) in C:\projects\requestplex\PlexRequests.UI\Startup.cs:line 59
```
There is nothing on my C from PlexRequests.net.

 Also:

```
2016/10/10 02:36:38.406 PlexRequests.UI.Program Fatal: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileLoadException: Could not load file or assembly 'file:///D:\PlexRequest\Ninject.Extensions.ChildKernel.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515) ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
``` 

```
System.InvalidOperationException: There is an error in XML document (1, 2). ---> System.InvalidOperationException: was not expected. at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexLibraries.Read4_MediaContainer() --- End of inner exception stack trace --- at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events) at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader) at PlexRequests.Api.ApiRequest.DeserializeXml[T](String input) in C:\projects\requestplex\PlexRequests.Api\ApiRequest.cs:line 138
```
again, i have PlexRequests on my D: not C:
and
```
Did not find any libraries in Plex.	PlexRequests.Services.Jobs.PlexAvailabilityChecker	Debug	10-10-2016 04:11:11
```

**Comment by tidusjar** [comment]
All the errors looks like you do not have it correctly configured. 

What OS are you running and are you sure your Plex settings are correct?

**Comment by KamakaziSanne** [comment]
I use windows, latest PlexRequests.net and nssm.
I have plex and request on the same PC in the same dir.
If i click "test connectivity" it says "connected to Plex succesfully"

i tried at "Plex Hostname or IP" my intern and extern ip/hostname and port but get the same results.

**Comment by tidusjar** [comment]
Can you just navigate to Plex, click on an episode/movie and press Get Info, then View XML

In the URL you should see your Plex API key. Can you make sure that matches what's in your settings?

**Comment by KamakaziSanne** [comment]
Plex Auth. key in PlexRequests.net = ihzMhtphmKah1SyM6p4p
And link for plex = 
`https://***-***-1-137.654fb5bda36142e0b7e450a04352ae49.plex.direct:32400/library/metadata/107522?checkFiles=1&includeExtras=1&X-Plex-Token=mdkFg3D2zV6syYZsUgNz`

**Comment by tidusjar** [comment]
Strange, change it to mdkFg3D2zV6syYZsUgNz

**Comment by KamakaziSanne** [comment]
did that and restarted PlexRequests.net but still same.

```
2016/10/10 11:06:00.419 PlexRequests.UI.Program Trace: Getting startup Port 
2016/10/10 11:06:00.520 PlexRequests.UI.Program Trace: Port: 3579 
2016/10/10 11:06:01.793 PlexRequests.Services.Jobs.CouchPotatoCacher Trace: Getting the settings 
2016/10/10 11:06:01.793 PlexRequests.Services.Jobs.StoreBackup Trace: Starting DB Backup 
2016/10/10 11:06:01.793 PlexRequests.Services.Jobs.SickRageCacher Trace: Getting the settings 
2016/10/10 11:06:01.793 PlexRequests.UI.Program Info: This is not Mono 
2016/10/10 11:06:02.337 PlexRequests.Services.Jobs.StoreBackup Trace: Starting DB Cleanup 
2016/10/10 11:06:03.028 PlexRequests.Api.ApiRequest Error: System.InvalidOperationException: There is an error in XML document (1, 2). ---> System.InvalidOperationException: <html xmlns=''> was not expected.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexLibraries.Read4_MediaContainer()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at PlexRequests.Api.ApiRequest.DeserializeXml[T](String input) in C:\projects\requestplex\PlexRequests.Api\ApiRequest.cs:line 138 System.InvalidOperationException: There is an error in XML document (1, 2). ---> System.InvalidOperationException: <html xmlns=''> was not expected.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexLibraries.Read4_MediaContainer()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at PlexRequests.Api.ApiRequest.DeserializeXml[T](String input) in C:\projects\requestplex\PlexRequests.Api\ApiRequest.cs:line 138
2016/10/10 11:06:03.083 PlexRequests.Services.Jobs.PlexAvailabilityChecker Debug: Did not find any libraries in Plex. 
```

**Comment by tidusjar** [comment]
Did you unblock the zip before extracting?

**Comment by KamakaziSanne** [comment]
yes.

**Comment by KamakaziSanne** [comment]
I don't know why but it works now, i changed something, but i think the plex-token was the problem after all.
