### ISSUE TITLE
Status page in admin give a API rate limit exceeded error

### ISSUE THREAD

**Issue by whitecollar17** [tidusjar/PlexRequests.Net#581]
If this is a bug report please make sure you have filled the following in:

#### Plex Requests.Net Version:
1.9.2

#### Operating System:
WIndows 10

#### Applicable Logs (from `/logs/` directory or the Admin page):
![image](https://cloud.githubusercontent.com/assets/2944704/19253309/82b1adca-8f4a-11e6-9b1c-ebb3cbac6dc6.png)
```


Logs go here (Please make sure you remove any personal information from the logs)
``Error Details

Nancy.RequestExecutionException: Oh noes! ---> Octokit.RateLimitExceededException: API rate limit exceeded for XXX.XXX.XXX.XXXX. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
   at Octokit.Connection.HandleErrors(IResponse response) in C:\Users\shiftkey\Documents\GitHub\octokit.net\Octokit\Http\Connection.cs:line 570
   at Octokit.Connection.d__52.MoveNext() in C:\Users\shiftkey\Documents\GitHub\octokit.net\Octokit\Http\Connection.cs:line 552
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.Connection.d__51`1.MoveNext() in C:\Users\shiftkey\Documents\GitHub\octokit.net\Octokit\Http\Connection.cs:line 537
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiConnection.d__33`1.MoveNext() in C:\Users\shiftkey\Documents\GitHub\octokit.net\Octokit\Http\ApiConnection.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiConnection.<>c__DisplayClass13_0`1.<b__0>d.MoveNext() in C:\Users\shiftkey\Documents\GitHub\octokit.net\Octokit\Http\ApiConnection.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiPagination.d__0`1.MoveNext() in C:\Users\shiftkey\Documents\GitHub\octokit.net\Octokit\Clients\ApiPagination.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PlexRequests.Core.StatusChecker.d__6.MoveNext() in C:\projects\requestplex\PlexRequests.Core\StatusChecker.cs:line 50
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PlexRequests.Core.StatusChecker.d__7.MoveNext() in C:\projects\requestplex\PlexRequests.Core\StatusChecker.cs:line 62
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PlexRequests.UI.Modules.AdminModule.<>c__DisplayClass101_0.<b__0>d.MoveNext() in C:\projects\requestplex\PlexRequests.UI\Modules\AdminModule.cs:line 563
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PlexRequests.Helpers.MemoryCacheProvider.d__4`1.MoveNext() in C:\projects\requestplex\PlexRequests.Helpers\MemoryCacheProvider.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PlexRequests.UI.Modules.AdminModule.d__101.MoveNext() in C:\projects\requestplex\PlexRequests.UI\Modules\AdminModule.cs:line 563
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PlexRequests.UI.Modules.AdminModule.<<-ctor>b__82_20>d.MoveNext() in C:\projects\requestplex\PlexRequests.UI\Modules\AdminModule.cs:line 185
   --- End of inner exception stack trace ---
   at Nancy.NancyEngine.InvokeOnErrorHook(NancyContext context, ErrorPipeline pipeline, Exception ex)`


#### Reproduction Steps:

Klick on status page after updating.  its give me a white page with a 500 error

**Comment by tidusjar** [comment]
There is not much I can do about this, you have somehow exceeded the github API limit. It does reset after a few minutes.
