### ISSUE TITLE
Admin panel and usermanagement page doesn't work

### ISSUE THREAD

**Issue by SuperPotatoMen** [tidusjar/PlexRequests.Net#684]
After clicking the admin panel i got a 500 internal server error.

This error is with a existing database

```
Error Details

Nancy.RequestExecutionException: Oh noes! ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at PlexRequests.UI.Helpers.SecurityExtensions.HasPermissionsRedirect(Permissions perm, NancyContext context, String routeName, HttpStatusCode code) in C:\projects\requestplex\PlexRequests.UI\Helpers\SecurityExtensions.cs:line 145
   at PlexRequests.UI.Modules.AdminModule.<.ctor>b__85_0(NancyContext ctx) in C:\projects\requestplex\PlexRequests.UI\Modules\Admin\AdminModule.cs:line 158
   at Nancy.BeforePipeline.<>c__DisplayClass4.b__3(NancyContext ctx, CancellationToken ct)
   --- End of inner exception stack trace ---
   at Nancy.NancyEngine.InvokeOnErrorHook(NancyContext context, ErrorPipeline pipeline, Exception ex)
```

On the usermanagement page i got this 500 internal server error:

```
Error Details

Nancy.RequestExecutionException: Oh noes! ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at PlexRequests.UI.Helpers.SecurityExtensions.HasPermissionsRedirect(Permissions perm, NancyContext context, String routeName, HttpStatusCode code) in C:\projects\requestplex\PlexRequests.UI\Helpers\SecurityExtensions.cs:line 145
   at PlexRequests.UI.Modules.UserManagementModule.<.ctor>b__0_0(NancyContext ctx) in C:\projects\requestplex\PlexRequests.UI\Modules\UserManagementModule.cs:line 29
   at Nancy.BeforePipeline.<>c__DisplayClass4.b__3(NancyContext ctx, CancellationToken ct)
   --- End of inner exception stack trace ---
   at Nancy.NancyEngine.InvokeOnErrorHook(NancyContext context, ErrorPipeline pipeline, Exception ex)
```

Issue page error:

```
Nancy.RequestExecutionException: Oh noes! ---> System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at RazorOutput.RazorView.Execute()
   at Nancy.ViewEngines.Razor.NancyRazorViewBase`1.ExecuteView(String body, IDictionary`2 sectionContents)
   at CallSite.Target(Closure , CallSite , Object , Object , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at CallSite.Target(Closure , CallSite , Object , Object , Object )
   at Nancy.ViewEngines.Razor.RazorViewEngine.<>c__DisplayClass2b.b__2a(Stream stream)
   at Nancy.Responses.MaterialisingResponse.PreExecute(NancyContext context)
   --- End of inner exception stack trace ---
   at Nancy.NancyEngine.InvokeOnErrorHook(NancyContext context, ErrorPipeline pipeline, Exception ex)
```

**Comment by tidusjar** [comment]
Fixed.
