### ISSUE TITLE
migration error after starting up

### ISSUE THREAD

**Issue by SuperPotatoMen** [tidusjar/PlexRequests.Net#704]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
Last dev build 1.10.0

#### Operating System:
Windows 10

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Starting Up! Please wait, this can usually take a few seconds.
Version: 1.10.0
Location of the database: C:\plexrequest dev\PlexRequests.sqlite
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at PlexRequests.Core.Migration.Migrations.Version1100.<>c__DisplayClass34_0.<MigrateUserNotifications>b__0(PlexUsers x) in C:\projects\requestplex\PlexRequests.Core.Migration\Migrations\Version1100.cs:line 97
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at PlexRequests.Core.Migration.Migrations.Version1100.MigrateUserNotifications() in C:\projects\requestplex\PlexRequests.Core.Migration\Migrations\Version1100.cs:line 97
   at PlexRequests.Core.Migration.Migrations.Version1100.Start(IDbConnection con) in C:\projects\requestplex\PlexRequests.Core.Migration\Migrations\Version1100.cs:line 85
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at PlexRequests.Core.Migration.MigrationRunner.MigrateToLatest() in C:\projects\requestplex\PlexRequests.Core.Migration\MigrationRunner.cs:line 43
   at PlexRequests.UI.Startup.Configuration(IAppBuilder app) in C:\projects\requestplex\PlexRequests.UI\Startup.cs:line 101
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Owin.Loader.DefaultLoader.<>c__DisplayClass12.<MakeDelegate>b__b(IAppBuilder builder)
   at Owin.Loader.DefaultLoader.<>c__DisplayClass1.<LoadImplementation>b__0(IAppBuilder builder)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.ResolveApp(StartContext context)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
   at Microsoft.Owin.Hosting.Starter.DirectHostingStarter.Start(StartOptions options)
   at Microsoft.Owin.Hosting.Starter.HostingStarter.Start(StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.StartImplementation(IServiceProvider services, StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.Start(StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.Start[TStartup](StartOptions options)
   at PlexRequests.UI.Program.Main(String[] args) in C:\projects\requestplex\PlexRequests.UI\Program.cs:line 93

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at PlexRequests.Core.Migration.Migrations.Version1100.<>c__DisplayClass34_0.<MigrateUserNotifications>b__0(PlexUsers x) in C:\projects\requestplex\PlexRequests.Core.Migration\Migrations\Version1100.cs:line 97
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at PlexRequests.Core.Migration.Migrations.Version1100.MigrateUserNotifications() in C:\projects\requestplex\PlexRequests.Core.Migration\Migrations\Version1100.cs:line 97
   at PlexRequests.Core.Migration.Migrations.Version1100.Start(IDbConnection con) in C:\projects\requestplex\PlexRequests.Core.Migration\Migrations\Version1100.cs:line 85
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at PlexRequests.Core.Migration.MigrationRunner.MigrateToLatest() in C:\projects\requestplex\PlexRequests.Core.Migration\MigrationRunner.cs:line 43
   at PlexRequests.UI.Startup.Configuration(IAppBuilder app) in C:\projects\requestplex\PlexRequests.UI\Startup.cs:line 101
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Owin.Loader.DefaultLoader.<>c__DisplayClass12.<MakeDelegate>b__b(IAppBuilder builder)
   at Owin.Loader.DefaultLoader.<>c__DisplayClass1.<LoadImplementation>b__0(IAppBuilder builder)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.ResolveApp(StartContext context)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
   at Microsoft.Owin.Hosting.Starter.DirectHostingStarter.Start(StartOptions options)
   at Microsoft.Owin.Hosting.Starter.HostingStarter.Start(StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.StartImplementation(IServiceProvider services, StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.Start(StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.Start[TStartup](StartOptions options)
   at PlexRequests.UI.Program.Main(String[] args) in C:\projects\requestplex\PlexRequests.UI\Program.cs:line 125

```

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by SuperPotatoMen** [comment]
I'm not sure if the reason that the migration failed beceause i have run a previous 1.10.0 build already.
