### ISSUE TITLE
Migration problem

### ISSUE THREAD

**Issue by seanvree** [tidusjar/PlexRequests.Net#769]
Trying to run BETA build on Windows 10 Pro. 

 Had the old version running just fine.

This is the error from Windows event logs:
Faulting application name: PlexRequests.exe, version: 1.10.1069.0, time stamp: 0x584e6371 Faulting module name: KERNELBASE.dll, version: 10.0.14393.479, time stamp: 0x58256d37 Exception code: 0xe0434352 Fault offset: 0x000da832 Faulting process id: 0x4988 Faulting application start time: 0x01d2550ac1f00944 Faulting application path: C:\PlexRequests\PlexRequests.exe Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll Report Id: c3c2bbcb-fa17-4204-9a40-77f63bf9517f Faulting package full name: Faulting package-relative application ID:

**Comment by tidusjar** [comment]
What's the error in the console?

**Comment by seanvree** [comment]
@tidusjar PlexRequests.ui has stopped working

**Comment by tidusjar** [comment]
There is nothing else? Are there other entries in the Event Viewer? There is usually a warning just after or before the above entry you posted.

**Comment by seanvree** [comment]
My original OP was the entry in the event viewer.

**Comment by tidusjar** [comment]
Ok... Did you follow the installation guides? Unblocked the .zip? Either registered the URL (urlacl) or run as Admin?

**Comment by seanvree** [comment]
yup. All I did was unblock the .zip. Extract to the current installation...that didn't work, so I created a new dir and extracted to there.  I mean, hard to screw that up, right?  There's another dude on Reddit who's having the same issue. 

https://www.reddit.com/r/PleX/comments/5haqbd/plexrequestnet_open_beta_1100/db4tjoa/

**Comment by seanvree** [comment]
Oh, crap, hang on....

**Comment by SuperPotatoMen** [comment]
Labeld with priority because it is a migration issue.

**Comment by tidusjar** [comment]
Do you know the exact version you are running (the version downloaded from AppVeyor) ?

There is a later version (built just now) can you try that?

**Comment by seanvree** [comment]
https://ci.appveyor.com/project/tidusjar/requestplex/build/1.10.1037

**Comment by tidusjar** [comment]
Yes that's correct

**Comment by seanvree** [comment]
No dice.  

Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>cd C:\plexrequests.net

C:\plexrequests.net>plexrequests.exe
Starting Up! Please wait, this can usually take a few seconds.
Version: 1.10.1075
Location of the database: C:\plexrequests.net\PlexRequests.sqlite
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at PlexRequests.Core.Migration.Migrations.Version1100.UpdateDb(IDbConnection con) in C:\projects\requestplex\PlexRequests.Core.Migration\Migrations\Version1100.cs:line 247
   at PlexRequests.Core.Migration.Migrations.Version1100.Start(IDbConnection con) in C:\projects\requestplex\PlexRequests.Core.Migration\Migrations\Version1100.cs:line 76
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at PlexRequests.Core.Migration.MigrationRunner.MigrateToLatest() in C:\projects\requestplex\PlexRequests.Core.Migration\MigrationRunner.cs:line 43
   at PlexRequests.UI.Startup.Configuration(IAppBuilder app) in C:\projects\requestplex\PlexRequests.UI\Startup.cs:line 101
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Owin.Loader.DefaultLoader.<>c__DisplayClass12.<MakeDelegate>b__b(IAppBuilder builder)
   at Owin.Loader.DefaultLoader.<>c__DisplayClass1.<LoadImplementation>b__0(IAppBuilder builder)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.ResolveApp(StartContext context)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
   at Microsoft.Owin.Hosting.Starter.DirectHostingStarter.Start(StartOptions options)
   at Microsoft.Owin.Hosting.Starter.HostingStarter.Start(StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.StartImplementation(IServiceProvider services, StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.Start(StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.Start[TStartup](StartOptions options)
   at PlexRequests.UI.Program.Main(String[] args) in C:\projects\requestplex\PlexRequests.UI\Program.cs:line 93

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at PlexRequests.Core.Migration.Migrations.Version1100.UpdateDb(IDbConnection con) in C:\projects\requestplex\PlexRequests.Core.Migration\Migrations\Version1100.cs:line 247
   at PlexRequests.Core.Migration.Migrations.Version1100.Start(IDbConnection con) in C:\projects\requestplex\PlexRequests.Core.Migration\Migrations\Version1100.cs:line 76
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at PlexRequests.Core.Migration.MigrationRunner.MigrateToLatest() in C:\projects\requestplex\PlexRequests.Core.Migration\MigrationRunner.cs:line 43
   at PlexRequests.UI.Startup.Configuration(IAppBuilder app) in C:\projects\requestplex\PlexRequests.UI\Startup.cs:line 101
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Owin.Loader.DefaultLoader.<>c__DisplayClass12.<MakeDelegate>b__b(IAppBuilder builder)
   at Owin.Loader.DefaultLoader.<>c__DisplayClass1.<LoadImplementation>b__0(IAppBuilder builder)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.ResolveApp(StartContext context)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
   at Microsoft.Owin.Hosting.Starter.DirectHostingStarter.Start(StartOptions options)
   at Microsoft.Owin.Hosting.Starter.HostingStarter.Start(StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.StartImplementation(IServiceProvider services, StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.Start(StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.Start[TStartup](StartOptions options)
   at PlexRequests.UI.Program.Main(String[] args) in C:\projects\requestplex\PlexRequests.UI\Program.cs:line 125

**Comment by seanvree** [comment]
So, if I don't care about the db, and I just want to get it up and running, can I just run thru the wizard and re-set up everything?  

Also, is there .config file that would carry over all my settings (and not the db), or is that in the sqlite file?

**Comment by tidusjar** [comment]
Could you send me the db? tidusjar@gmail.com

The db is the sqlite file and that contains all of the config. You can just delete it and rerun through the wizard. But it would be useful if you could send it to me so I can fix the underlying issue

**Comment by seanvree** [comment]
@tidusjar , sent you the entire install folder from my gdrive.

I'm worried that if I run thru the setup again, and once the beta goes to master, then we'll have this issue again?

What do you think? Revert back to the old or re-set up everything?

**Comment by tidusjar** [comment]
Yeah that's why I wanted the database so I can fix this so no one else has this problem :)

Let me fix it and you should be good to go.

**Comment by seanvree** [comment]
wurd! no worries, it's BETA for a reason, right?

**Comment by tidusjar** [comment]
Here we go, currently compiling: https://ci.appveyor.com/project/tidusjar/requestplex/build/1.10.1078/artifacts

**Comment by seanvree** [comment]
@tidusjar , NICE! Let me know when I can test er out!

**Comment by seanvree** [comment]
@tidusjar , okay, that worked!

**Comment by SuperPotatoMen** [comment]
Cool!
