### ISSUE TITLE
Internal Server Error on EAP Branch (WINDOWS)

### ISSUE THREAD

**Issue by seanvree** [tidusjar/PlexRequests.Net#773]
Windows 10 U

Branch:  EAP: f7eec8be

Get the following when clicking on STATUS from the admin settings (everything else seems to work):

Nancy.RequestExecutionException: Oh noes! ---> Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'PlexRequests.Core.SettingModels.SystemSettings' does not contain a definition for 'UpdateAvailable'
   at CallSite.Target(Closure , CallSite , Object )
   at RazorOutput.RazorView.Execute()
   at Nancy.ViewEngines.Razor.NancyRazorViewBase`1.ExecuteView(String body, IDictionary`2 sectionContents)
   at CallSite.Target(Closure , CallSite , Object , Object , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at CallSite.Target(Closure , CallSite , Object , Object , Object )
   at Nancy.ViewEngines.Razor.RazorViewEngine.<>c__DisplayClass2b.b__2a(Stream stream)
   at Nancy.Responses.MaterialisingResponse.PreExecute(NancyContext context)
   --- End of inner exception stack trace ---
   at Nancy.NancyEngine.InvokeOnErrorHook(NancyContext context, ErrorPipeline pipeline, Exception ex)

**Comment by tidusjar** [comment]
This is because you overwrote all of the current files, unfortunately in the new release, it requires a clean installation and then copy over your DB.

This is because I made some changes to the project structure without thinking about the upgrade. Sorry about this, i'll make sure this doesn't happen in the future.

**Comment by seanvree** [comment]
@tidusjar, well that's easy, all I need to do is just make a fresh DIR, then copy the new files, then copy in my old .sqlite file, correct?

**Comment by tidusjar** [comment]
Correct!

**Comment by seanvree** [comment]
Well, that's easy when you're running from a source on Windows.
