### ISSUE TITLE
PlexRequests.net: Unexpected status SERVICE_STOPPED in response to START control.

### ISSUE THREAD

**Issue by whatupcraig** [tidusjar/PlexRequests.Net#781]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
1.10
#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Logs go here (Please make sure you remove any personal information from the logs)
```

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by whatupcraig** [comment]
This is just trying to ge the service to start. I ran nssm start PlexRequests.exe and it produced that error.

**Comment by tidusjar** [comment]
Can you post the error in the console when running it manually?

**Comment by juthrbog** [comment]
I am also getting the same error when running 'nssm start PlexRequests.Net'. I followed the steps outlined [here](http://www.htpcguides.com/install-plex-requests-net-windows-system-service/).

Uploaded a screenshot of the error when attempting to manually start via Services.

![plexrequestserror](https://cloud.githubusercontent.com/assets/24612570/21275239/cd6a2e40-c399-11e6-9ace-ed0a4ab964b1.PNG)

**Comment by tidusjar** [comment]
Can you manually start without the services?

**Comment by juthrbog** [comment]
Forgot to mention I'm running Windows 10 and the most recent version of PlexRequests.Net.

I tried running manually starting PlexRequests.exe and got the below.
![plexrequestserror1](https://cloud.githubusercontent.com/assets/24612570/21278603/3a1ee7fa-c3aa-11e6-8389-2a2d8c28a350.PNG)

**Comment by tidusjar** [comment]
Ah, it needs to be ran as admin

**Comment by juthrbog** [comment]
Set PlexRequests.exe to Run as Administrator for all users. Now when I try to manually start I get the below. The window just hangs and pressing a key doesn't do anything. I'm not able to connect to PlexRequests. Also tried starting via Services and NSSM, but continuing to get the same error. Tried removing the service and re-adding it, but the issue persists.

![plexrequestserror2](https://cloud.githubusercontent.com/assets/24612570/21282044/7aa46920-c3bf-11e6-8c91-9ac39a66c683.PNG)

**Comment by whatupcraig** [comment]
So this is what I get at the end of the command prompt if I try and run plex requests.

at PlexRequests.UI.Program.Main(String[] args) in C:\projects\requestplex\PlexRequests.UI\Program.cs:line 125

followed by the "PlexRequests.UI has stopped working" window.

**Comment by SuperPotatoMen** [comment]
Start plexrequest.net with admin rights. then leave the  command prompt, (It need to stay it open, its correct you can't typ something in it)
 now you need to browser to http://localhost:3579 (on the machine you run the plexrequest.net)

**Comment by whatupcraig** [comment]
![image](https://cloud.githubusercontent.com/assets/20756018/21290107/b98e8fe2-c46b-11e6-97d0-c5da2b45bf1b.png)

Even when i run it as admin it still crashes.

**Comment by tidusjar** [comment]
Did you unblock the zip file?

**Comment by whatupcraig** [comment]
I did. I even re downloaded it and made sure to unblock it before i unzipped the files.

**Comment by SuperPotatoMen** [comment]
Pleas don't printscreen (see my post before)  copypast the whole error in a post

**Comment by whatupcraig** [comment]
My bad. Here is the log.

Starting Up! Please wait, this can usually take a few seconds.
Version: 1.10.1086
Location of the database: C:\PlexStuff\PlexRequsts.net\PlexRequests.sqlite
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileLoadException: Could not load file or assembly 'file:///C:\PlexStuff\PlexRequsts.net\Ninject.Extensions.ChildKernel.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515) ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.

   --- End of inner exception stack trace ---
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Ninject.Modules.AssemblyNameRetriever.AssemblyChecker.GetAssemblyNames(IEnumerable`1 filenames, Predicate`1 filter)
   at Ninject.Modules.AssemblyNameRetriever.AssemblyChecker.GetAssemblyNames(IEnumerable`1 filenames, Predicate`1 filter)
   at Ninject.Modules.AssemblyNameRetriever.GetAssemblyNames(IEnumerable`1 filenames, Predicate`1 filter)
   at Ninject.Modules.CompiledModuleLoaderPlugin.LoadModules(IEnumerable`1 filenames)
   at Ninject.Modules.ModuleLoader.LoadModules(IEnumerable`1 patterns)
   at Ninject.KernelBase.Load(IEnumerable`1 filePatterns)
   at Ninject.KernelBase..ctor(IComponentContainer components, INinjectSettings settings, INinjectModule[] modules)
   at PlexRequests.UI.Startup.Configuration(IAppBuilder app) in C:\projects\requestplex\PlexRequests.UI\Startup.cs:line 101
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Owin.Loader.DefaultLoader.<>c__DisplayClass12.<MakeDelegate>b__b(IAppBuilder builder)
   at Owin.Loader.DefaultLoader.<>c__DisplayClass1.<LoadImplementation>b__0(IAppBuilder builder)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.ResolveApp(StartContext context)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
   at Microsoft.Owin.Hosting.Starter.DirectHostingStarter.Start(StartOptions options)
   at Microsoft.Owin.Hosting.Starter.HostingStarter.Start(StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.StartImplementation(IServiceProvider services, StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.Start(StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.Start[TStartup](StartOptions options)
   at PlexRequests.UI.Program.Main(String[] args) in C:\projects\requestplex\PlexRequests.UI\Program.cs:line 93

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileLoadException: Could not load file or assembly 'file:///C:\PlexStuff\PlexRequsts.net\Ninject.Extensions.ChildKernel.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515) ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.

   --- End of inner exception stack trace ---
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Ninject.Modules.AssemblyNameRetriever.AssemblyChecker.GetAssemblyNames(IEnumerable`1 filenames, Predicate`1 filter)
   at Ninject.Modules.AssemblyNameRetriever.AssemblyChecker.GetAssemblyNames(IEnumerable`1 filenames, Predicate`1 filter)
   at Ninject.Modules.AssemblyNameRetriever.GetAssemblyNames(IEnumerable`1 filenames, Predicate`1 filter)
   at Ninject.Modules.CompiledModuleLoaderPlugin.LoadModules(IEnumerable`1 filenames)
   at Ninject.Modules.ModuleLoader.LoadModules(IEnumerable`1 patterns)
   at Ninject.KernelBase.Load(IEnumerable`1 filePatterns)
   at Ninject.KernelBase..ctor(IComponentContainer components, INinjectSettings settings, INinjectModule[] modules)
   at PlexRequests.UI.Startup.Configuration(IAppBuilder app) in C:\projects\requestplex\PlexRequests.UI\Startup.cs:line 101
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Owin.Loader.DefaultLoader.<>c__DisplayClass12.<MakeDelegate>b__b(IAppBuilder builder)
   at Owin.Loader.DefaultLoader.<>c__DisplayClass1.<LoadImplementation>b__0(IAppBuilder builder)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.ResolveApp(StartContext context)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
   at Microsoft.Owin.Hosting.Starter.DirectHostingStarter.Start(StartOptions options)
   at Microsoft.Owin.Hosting.Starter.HostingStarter.Start(StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.StartImplementation(IServiceProvider services, StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.Start(StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.Start[TStartup](StartOptions options)
   at PlexRequests.UI.Program.Main(String[] args) in C:\projects\requestplex\PlexRequests.UI\Program.cs:line 125

**Comment by SuperPotatoMen** [comment]
Can you run the last release? 

Operation is not supported. (Exception from HRESULT: 0x80131515) ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.

**Comment by tidusjar** [comment]
Can you please right click and pres
Properties on the following file "Ninject.Extensions.ChildKernel.dll" and check if it's blocked?

**Comment by whatupcraig** [comment]
I downloaded the latest release. I am not sure exactly what it wanting me to do.

**Comment by whatupcraig** [comment]
It was blocked. I unblocked it and tried running it again but same thing. I looked at other files and they are blocked as well

**Comment by SuperPotatoMen** [comment]
It is blocked because you need to unblock the zip file first. After you did unzip the file

**Comment by SuperPotatoMen** [comment]
Wrong button :/

**Comment by whatupcraig** [comment]
I did unblock it. Two seperate times. I downloaded the file twice and unblocked it both times before unzipping. Still didnt work.

**Comment by whatupcraig** [comment]
This is one of the downloads. I unblocked it before i extracted the contents
![image](https://cloud.githubusercontent.com/assets/20756018/21290261/b1ddfa12-c470-11e6-8ac7-208ced2df86c.png)

**Comment by SuperPotatoMen** [comment]
Can we have a teamviewer session with Skype?

**Comment by whatupcraig** [comment]
ya my skype name is bailey_craig0

**Comment by whatupcraig** [comment]
Let me know when you want to skype. I'll be available most of the evening.

**Comment by SuperPotatoMen** [comment]
@whatupcraig i added you

**Comment by SuperPotatoMen** [comment]
okay, in a 2 hour session we found a problem with the nssm program, i can't access the plexrequest.net file.
If you start it manualy it is now all okay. I will close this one, beceause we don't give support on external programs to start plexrequest.net

**Comment by SuperPotatoMen** [comment]
After 2 hours skyping it is working now :D Excited!

**Comment by whatupcraig** [comment]
Lol. The sad part is we never definitely found out what the issue was. But glad it's working. Thanks again!
