### ISSUE TITLE
Not starting on server 2016

### ISSUE THREAD

**Issue by gldrenthe89** [tidusjar/PlexRequests.Net#789]
Hello.

I downloaded the latest release. But it isn't working see screenshot. 
I'm running Server 2016 x64 and followed the Windows Guide: http://www.htpcguides.com/install-plex-requests-net-windows-system-service/
![screenshot_2](https://cloud.githubusercontent.com/assets/6988259/21267948/f25497be-c3ac-11e6-9e9f-f4c2c3e3d903.jpg)

Can someone please help me

**Comment by SuperPotatoMen** [comment]
Pleas use our bug report form.

Did you unblock the rar file first? Other way PlexRequests.Net will crash on starting up

**Comment by gldrenthe89** [comment]
Sorry for not using the report form. 

Yes is did unblock it.

**Comment by gldrenthe89** [comment]
f this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version: PlexRequests v1.10.0

#### update Branch: unknown


#### Operating System: Server 2016


#### Mono Version: Not installed. is this needed?


#### Applicable Logs (from `/logs/` directory or the Admin page):

Starting Up! Please wait, this can usually take a few seconds.
Version: 1.10.1086
Location of the database: C:\PlexRequests.net\PlexRequests.sqlite
no configuration section <common/logging> found - suppressing logging output
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.HttpListenerException: Access is denied
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at Microsoft.Owin.Host.HttpListener.OwinHttpListener.Start(HttpListener listener, Func`2 appFunc, IList`1 addresses, IDictionary`2 capabilities, Func`2 loggerFactory)
   at Microsoft.Owin.Host.HttpListener.OwinServerFactory.Create(Func`2 app, IDictionary`2 properties)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Owin.Hosting.ServerFactory.ServerFactoryAdapter.Create(IAppBuilder builder)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.StartServer(StartContext context)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
   at Microsoft.Owin.Hosting.Starter.DirectHostingStarter.Start(StartOptions options)
   at Microsoft.Owin.Hosting.Starter.HostingStarter.Start(StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.StartImplementation(IServiceProvider services, StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.Start(StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.Start[TStartup](StartOptions options)
   at PlexRequests.UI.Program.Main(String[] args) in C:\projects\requestplex\PlexRequests.UI\Program.cs:line 93

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.HttpListenerException: Access is denied
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at Microsoft.Owin.Host.HttpListener.OwinHttpListener.Start(HttpListener listener, Func`2 appFunc, IList`1 addresses, IDictionary`2 capabilities, Func`2 loggerFactory)
   at Microsoft.Owin.Host.HttpListener.OwinServerFactory.Create(Func`2 app, IDictionary`2 properties)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Owin.Hosting.ServerFactory.ServerFactoryAdapter.Create(IAppBuilder builder)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.StartServer(StartContext context)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
   at Microsoft.Owin.Hosting.Starter.DirectHostingStarter.Start(StartOptions options)
   at Microsoft.Owin.Hosting.Starter.HostingStarter.Start(StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.StartImplementation(IServiceProvider services, StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.Start(StartOptions options)
   at Microsoft.Owin.Hosting.WebApp.Start[TStartup](StartOptions options)
   at PlexRequests.UI.Program.Main(String[] args) in C:\projects\requestplex\PlexRequests.UI\Program.cs:line 125


```
Logs go here (Please make sure you remove any personal information from the logs)
```


#### Reproduction Steps:

Starting PlexRequest.exe

**Comment by gldrenthe89** [comment]
The directory: C:\projects\requestplex\PlexRequests.UI doesn't exists. That's normal?

**Comment by tidusjar** [comment]
You need to run as admin

**Comment by gldrenthe89** [comment]
I already did that trick. Doesn't work either
